{{
    config(
        alias = 'customermaster_base_68_mapped'

    )
}}


SELECT

CASE 
    WHEN T2.TUCCUSTSS IS NOT NULL 
     AND T2.TUCCUSTSS != '' THEN T2.TUCCUSTSS 
    ELSE NULL 
END AS TUCCUSTOR_46,
    
t1.TUCSALESG,
t1.TNSALEORG,
t1.SOURSYSTEM,
t1.OBJVERS,
t1.TNCBPCUST,
t1.TNCBPCUST_TEXT,
t1.TNECUSNU,
t1.TNCNAME,
t1.TNCINDUSTY,
t1.TNCPOSTLCD,
t1.TNCCITY,
t1.TNCSTREET,
t1.TNCREGION,
t1.TNCTELNUM,
t1.TNCCOUNTRY,
t1.TNCDELINDC,
t1.CREATEDON,
t1.TNCCUSTYP,
T2.TUCHIEA02,
T2.TUCHIEA01,
T2.TUCHIEA03,
T2.TUCHIEB03,
T2.TUCCUSTGP,
T3.TUCKONZS,
T3."TUCNAMEE" AS GROUPKEYNAME,
T3.TUCINDUSY
FROM {{ ref('customermaster_base_68') }} AS T1

LEFT JOIN {{ ref('tuccustss_view') }} AS T2
  ON T1.TUCSALESG = T2.TUCSALESG
  AND T1.TNECUSNU = T2.TUCCUSTSS

LEFT JOIN {{ ref('tuccustor_view') }} AS T3
  ON T2.TUCCUSTSS = T3.TUCCUSTOR AND T3.SOURSYSTEM = 'A2'


