{{
    config(
        alias = 'customer_master_view'

    )
}}

SELECT 
MD5(CONCAT(T1.SOURSYSTEM,T1.TNSALEORG,T1.TNSALEORG,'00','01',T1.TNCBPCUST)) AS PKEY_CUSTOMER,
T1.SOURSYSTEM AS SOURSYSTEM,
T1.TNSALEORG AS TUCSALESG,
T1.TNSALEORG AS TUCCOMPCE,
'00' AS TUCDIVISN,
'01' AS TUCDISTRN,
T1.TNCBPCUST AS TNCCUSTOR,
T1.TUCCUSTOR_46 AS TUCCUSTOR_46,
NVL(T1.TUCCUSTOR_46,TNCBPCUST) AS TUCCUSTOR_COMBINED,
T1.TNCBPCUST AS TUCCUSTOR_68,
NULL AS ACCOUNT_CLOSURE,
NULL AS DELETION_FLAG,
NULL AS TUCPACFLG,
NULL AS TUCPACFLG_UPDATE_DATE,
NULL AS CLUSTER,
NULL AS CE_SEGMENT_TEXT,
NULL AS CE_SEGMENT_ID,
NULL AS CE_PERIOD_START,
NULL AS CE_PERIOD_END,
NULL AS LIFECYCLE_STAGE,
NULL AS LIFECYCLE_LABEL,
NULL AS LIFECYCLE_STAGE_UPDATE_DATE,
NULL AS LIFECYCLE_STAGE_CISCO,
NULL AS LIFECYCLE_STAGE_CISCO_UPDATE_DATE,
NULL AS TUCTSCUSS,
NULL AS GROUPKEY_ADJ,
NULL AS DNB_DUNS_NBR,
NULL AS DNB_CONFIDENCE_CODE,
NULL AS DNB_NAME_SCORE,
NULL AS DNB_CITY_SCORE,
NULL AS DNB_STATE_SCORE,
NULL AS DNB_STRNAME_SCORE,
NULL AS DNB_STRNUMB_SCORE,
NULL AS DNB_PHONE_SCORE,
NULL AS DNB_POBOX_SCORE,
NULL AS TNCACCNTP,
NULL AS TNCADDRNR,
T1.TNCCITY AS TNCCITYY,
T1.TNCCOUNTRY AS TNCCOUNTY,
NULL AS TNCCUSTCS,
NULL AS TNCCOUNTE,
NULL AS TNCCUSFCS,
T1.TNCDELINDC AS TUCDELINC_TUCCUSTOR,
NULL AS TUCDBDUNM,
NULL AS TUCFAXNUM,
T1.TUCINDUSY AS TUCINDUSY,
T6."/BIC/TUCINDUSY" AS TUCINDUSY_TEXT,
NULL AS TUCINDCO1,
NULL AS TUCINDCO2,
NULL AS TUCINDCO3,
NULL AS TUCINDCO4,
NULL AS TUCINDCO5,
NULL AS LANGU,
T1.TNCNAME AS TUCNAMEE,
NULL AS TUCNAME22,
NULL AS TUCNAME33,
NULL AS TUCNIELSD,
NULL AS TUCPCOMPY,
T1.TNCTELNUM AS TUCPHONEE,
NULL AS TUCPLANTT_TUCCUSTOR,
NULL AS TUCPOBOXX,
T1.TNCPOSTLCD AS TUCPOSTAD,
NULL AS TUCPOSTCX,
NULL AS TUCPOSTCS,
T1.TNCREGION AS TUCREGION,
T1.TNCSTREET AS TUCSTREET,
NULL AS TUCSORTLL,
NULL AS TUCTAXNUB,
NULL AS TUCTAXNU2,
NULL AS TUCUSAGED,
NULL AS TUCVENDOR,
NULL AS TUCAUFSD_TUCCUSTOR,
NULL AS TUCBBBNR,
NULL AS TUCBBSNR,
NULL AS TUCBUBKZ,
NULL AS TUCEMAILX,
T1.CREATEDON AS TUDERDATX,
NULL AS TUCFAKSD_TUCCUSTOR,
NULL AS TUCGFORM,
NULL AS TUCHZUOR,
NULL AS TUCKATR1,
NULL AS TUCKATR6,
NULL AS TUCKDKG3,
NULL AS TUCKDKG4,
NULL AS TUCLIFSD_TUCCUSTOR,
NULL AS TUCLZONE,
NULL AS TUCNAME4,
NULL AS TUCORT2,
NULL AS TUCPFORT,
NULL AS TUCSTCEG,
NULL AS TUCTELBX,
NULL AS TUCTELFX,
NULL AS TUCTTXNUM,
NULL AS TUCVATCOU,
NULL AS TUCZZGMNR,
NULL AS TUCSTREE4,
NULL AS TUCDATLIN,
NULL AS TUKUMSA1,
NULL AS TUYUWAERR,
NULL AS FISCVARNT,
NULL AS TUCNONVAT,
NULL AS TUCECG,
NULL AS TUCKFTBUS,
NULL AS TUCKFTIND,
NULL AS TUCBPARTR,
NULL AS TUCKDKG5,
NULL AS TUCHUNST,
NULL AS TUCMETXJD,
NULL AS TUCELMTET,
NULL AS TUCSTCD3,
NULL AS TUCBEGRU_TUCCUSTOR,
NULL AS TUCDBA1,
NULL AS TUCDBA2,
NULL AS TUCDTAWS,
NULL AS TUCKATR9,
NULL AS TUCVENCLN_TUCCUSTOR,
NULL AS TUCVENCLS_TUCCUSTOR,
T1.TNCBPCUST AS TUCCUSTCC,
NULL AS TUCBUSABD,
NULL AS TUCKNRMA,
NULL AS TUCCCTRAA_TUCCUSTCC,
NULL AS TUCDELINC_TUCCUSTCC, 
NULL AS TUCEMPLOE,
NULL AS TUCPMNTTS_TUCCUSTCC,
NULL AS TUCPMNTBK,
NULL AS TUCPMTMTL,
NULL AS TUCALTKN,
NULL AS TUCBUSAB,
NULL AS TUCCRBLB,
NULL AS TUCCTLPC,
NULL AS TUCDBRTG,
NULL AS TUDGMVDTT,
NULL AS TUCGRUPP,
NULL AS TUCKNRZE,
NULL AS TUCKVERM,
NULL AS TUCPERKZ,
NULL AS TUCSBGRP,
NULL AS TUCTOGRU,
NULL AS TUDVERDTT,
NULL AS TUCVRBKZ,
NULL AS TUCVRSNR,
NULL AS TUCVZSKZ,
NULL AS TUCWAKON,
NULL AS TUCXAUSZ,
NULL AS TUCZWELS,
NULL AS TUCGUZTE,
NULL AS TUCINTADR,
NULL AS TUKCUCRLI,
NULL AS TUKHORREC,
NULL AS TUKRECORD_TUCCUSTCC,
NULL AS TUKTOTREC,
NULL AS TUKVLIBB,
NULL AS TUKWRTAK,
NULL AS TUKGENINO,
NULL AS TUYWAERSX,
NULL AS CURRENCY_TUCCUSTCC,
NULL AS TUCRCACCT,
NULL AS TUCCHRTAS,
NULL AS TUCKNKLI,
NULL AS TUCFCFDGP,
NULL AS TUCCRMAN,
NULL AS TUCGROREL,
NULL AS TUCBEGRU_TUCCUSTCC,
NULL AS TUCZUAWA,
NULL AS TUCALTKNA,
NULL AS TUCCADUNC,
NULL AS TUCLOCKB,
NULL AS TUCPRACCT,
NULL AS TUDNEXTRV,
NULL AS TUDLASTDN,
NULL AS TUCDUNNLL,
NULL AS TUCDUNNBK,
T1.TNCBPCUST AS TUCCUSTSS,
NULL AS TUDLBILDA,
NULL AS TUCVENCLS_TUCCUSTSS,
NULL AS TUCVENCLN_TUCCUSTSS,
T1.TNCCUSTYP AS TUCACCNTN,
NULL AS TUCCUSTCA,
NULL AS TUCCUSTGP,
NULL AS TUCCUSTG1,
NULL AS TUCCUSTG2,
NULL AS TUCCUSTG2_TEXT,
NULL AS TUCCUSTG3,
NULL AS TUCCUSTG4,
NULL AS TUCCUSTG5,
NULL AS TUCCCTRAA_TUCCUSTSS,
NULL AS TUCDELINC_TUCCUSTSS, 
NULL AS TUCINCOTS,
NULL AS TUCINCOT2,
NULL AS TUCPLANTT_TUCCUSTSS,
NULL AS TUCPMNTTS_TUCCUSTSS,
NULL AS TUCSALEST,
NULL AS TUCSALESP,
NULL AS TUCSALESF,
NULL AS TUCAKTIV,
NULL AS TUCAUFSD_TUCCUSTSS,
NULL AS TUCCUSCL,
NULL AS TUCBOKRE,
NULL AS TUCEDGRP,
NULL AS TUCEDSTA,
NULL AS TUCFAKSD_TUCCUSTSS,
NULL AS TUCFLLOGO,
NULL AS TUDFODATE,
NULL AS TUCGFLAG,
NULL AS TUCGVFCO,
T1.TUCHIEA01 AS TUCHIEA01,
T1.TUCHIEA02 AS TUCHIEA02,
T1.TUCHIEA03 AS TUCHIEA03,
NULL AS TUCHIEB01,
NULL AS TUCHIEB02,
T1.TUCHIEB03 AS TUCHIEB03,
NULL AS TUCHIEC01,
NULL AS TUCHIEC02,
NULL AS TUCHIEC03,
NULL AS TUCHIEC04,
NULL AS TUCHIED01,
NULL AS TUCHIED02,
NULL AS TUCHIED03,
NULL AS TUCHIED04,
NULL AS TUCHIEE01,
NULL AS TUCHIEE02,
NULL AS TUCHIEE03,
NULL AS TUCHIEE04,
NULL AS TUCHIEF01,
NULL AS TUCHIEF02,
NULL AS TUCHIEF03,
NULL AS TUCHIEG01,
NULL AS TUCHIEG02,
NULL AS TUCHIEG03,
NULL AS TUCKALKS,
NULL AS TUCKONDA,
NULL AS TUCKZAZU,
NULL AS TUCKZTLF,
NULL AS TUDLEDORD,
NULL AS TUCLIFSD_TUCCUSTSS,
NULL AS TUDLITORD,
NULL AS TUDLORDDA,
NULL AS TUCLPRIO,
NULL AS TUCPERFK,
NULL AS TUCPLTYP,
NULL AS TUCPRAT5,
NULL AS TUCPRAT6,
NULL AS TUCPRAT7,
NULL AS TUDUDATEE,
NULL AS TUCVERSG,
NULL AS TUCVSBED,
NULL AS TUCWECOD,
NULL AS TUCZPRAT1,
NULL AS TUCZPRAT2,
NULL AS TUCZPRAT3,
NULL AS TUCZPRAT4,
NULL AS TUCZPRAT5,
NULL AS TUCZPRAT6,
NULL AS TUCZZDRBL,
NULL AS TUCZZPIBL,
NULL AS TUCKURST,
NULL AS TUKRECORD_TUCCUSTSS,
NULL AS CURRENCY_TUCCUSTSS,
NULL AS TUCPODREL,
NULL AS TUCCUABC,
NULL AS TUCHPCL,
NULL AS TUCFRDS,
NULL AS TUCZPRAT7,
NULL AS TUCHIEH01,
NULL AS TUCHIEH02,
NULL AS TUCHIEH03,
NULL AS TUCTELCO,
NULL AS TUCDIGSIG,
NULL AS TUKPAML,
NULL AS CE_PAM_EUR,
NULL AS TUDPAMLUU,
NULL AS TUYLOCCUY,
NULL AS TUCTCDGRP,
NULL AS TUCZORPRI,
NULL AS TUCPVKSM,
NULL AS TUCINVSOU,
NULL AS TUCUSEXFL,
NULL AS TUCFRFWFL,
NULL AS TUCZPRA12,
NULL AS TUCZPRA13,
NULL AS TUCCUSUNV
FROM  {{ ref('customermaster_base_68_mapped') }}  AS T1
LEFT JOIN {{ source('us_cdp_bw_46','TUCINDUSY_TXT') }}  AS T6 
  ON T1.TUCINDUSY = T6."/BIC/TUCINDUSY"

--LEFT JOIN PACE.PRG_PACE_LASTPACEFLAG AS T2
    -- ON NVL(T1.TUCCUSTOR_46,T1.TPBPCUST) = T2.TUCCUSTOR 
    -- AND T1.TUCSALESG = T2.TUCSALESG

--LEFT JOIN EU_DATAPRACTICE.PAM.LAST_SEGMENTATION_WITH_EXCEPTIONS AS T3 
    -- ON T1.SOURSYSTEM = T3.SOURSYSTEM 
    -- AND T1.TPBPCUST = T3.TUCCUSTOR 
    -- AND T1.TUCSALESG = T3.TUCSALESG

--LEFT JOIN PACE.PRG_PACE_LASTLIFECYCLESTAGE AS T4 
    -- ON NVL(T1.TUCCUSTOR_46,T1.TPBPCUST) = T4.TUCCUSTOR 
    -- AND T1.TUCSALESG = T4.TUCCOMPCE
    
--LEFT JOIN PACE.LIFECYCLE AS T4_2 
    -- ON T4.LIFECYCLE_STAGE = T4_2.LIFECYCLE_CODE
    
--LEFT JOIN PACE.PRG_PACE_LASTPACECLUSTER AS T5 
    -- ON NVL(T1.TUCCUSTOR_46,T1.TPBPCUST) = T5.TUCCUSTOR 
    -- AND T1.TUCSALESG = T5.TUCCOMPCE

--LEFT JOIN DNB.DNB_MAP_FACT AS T7 
    -- ON T1.TPBPCUST = T7.DOC_ID_1 
    -- AND T7.WORKFLOW = 'TDE_CUSTOMERMASTER_RESELLER' 
    -- AND T7.TD_REGION = 'EMEA_6.8' 
    -- AND T7.DNB_CONFIDENCE_CODE >= 7

--LEFT JOIN USER_ZUZANA_SZABOVA.PRG_CUSTOMERMASTER_MAPPING_68_46 AS T2 
    -- ON T1.TUCSALESG = T2.TUCSALESG 
    -- AND T1.TPBPCUST = T2.TPBPCUST
    
--LEFT JOIN EU_ANALYTICS_PROD.TUCCUSTOR AS T3 
    -- ON T2.GROUPKEY_ADJ = T3.TUCCUSTOR 
    -- AND T3.SOURSYSTEM = 'P1'
    
--LEFT JOIN EU_ANALYTICS_PROD.TUCCUSTSS AS T4 
    -- ON T2.GROUPKEY_ADJ = T4.TUCCUSTSS 
    -- AND T1.TUCSALESG = T4.TUCSALESG 
    -- AND T4.SOURSYSTEM = 'P1' 
    -- AND T4.TUCDISTRN = '00' 
    -- AND T4.TUCDIVISN = '10' 
    
--LEFT JOIN (SELECT * FROM 
--(SELECT COMPANY_CODE, RESELLER_ID, GLBL_MFR, LIFECYCLE_VALUE 
   --FROM PACE_VENDOR.VENDOR_LAST_LIFECYCLE) AS T
   --PIVOT(MAX(LIFECYCLE_VALUE) FOR GLBL_MFR IN ('CISCO')) AS P 
   -- (COMPANY_CODE, RESELLER_ID, LIFECYCLE_STAGE_CISCO )) AS T8 
   -- ON  NVL(T1.TUCCUSTOR_46,T1.TPBPCUST) = T8.RESELLER_ID 
   -- AND T1.TUCSALESG = T8.COMPANY_CODE

--LEFT JOIN (SELECT * FROM 
--(SELECT COMPANY_CODE, RESELLER_ID, GLBL_MFR, DB_CREATED_DATE 
--      FROM PACE_VENDOR.VENDOR_LAST_LIFECYCLE) AS T
-- --PIVOT(MAX(DB_CREATED_DATE) FOR GLBL_MFR IN ('CISCO')) AS P
--   (COMPANY_CODE, RESELLER_ID, LIFECYCLE_STAGE_CISCO_UPDATE_DATE )) AS T9 
--      ON  NVL(T1.TUCCUSTOR_46,T1.TPBPCUST) = T9.RESELLER_ID 
--      AND T1.TUCSALESG = T9.COMPANY_CODE

UNION ALL

SELECT  MD5(CONCAT(T1.SOURSYSTEM,T2.TUCSALESG,T3."/BIC/TUCCOMPCE",T2.TUCDIVISN,T2.TUCDISTRN,T1.TUCCUSTOR)) AS PKEY_CUSTOMER,
T1.SOURSYSTEM,
T2.TUCSALESG,
T3."/BIC/TUCCOMPCE",
T2.TUCDIVISN,
T2.TUCDISTRN,
T1.TUCCUSTOR,
T1.TUCCUSTOR AS TUCCUSTOR_46,
T1.TUCCUSTOR AS TUCCUSTOR_COMBINED,
T4.TNCBPCUST AS TUCCUSTOR_68, 

CASE 
    WHEN T2.TUCHIEA03 IN ('0030001061') THEN TRUE 
    ELSE FALSE 
END AS ACCOUNT_CLOSURE,

CASE 
    WHEN T2.TUCHIEA03 IN ('0030001061') 
      OR T1.TUCDELINC = 'X'  THEN TRUE 
    ELSE FALSE 
END AS DELETION_FLAG,

NULL AS TUCPACFLG,
NULL AS TUCPACFLG_UPDATE_DATE,
NULL AS CLUSTER,
NULL AS CE_SEGMENT_TEXT,
NULL AS CE_SEGMENT_ID,
NULL AS CE_PERIOD_START,
NULL AS CE_PERIOD_END,
NULL AS LIFECYCLE_STAGE,
NULL AS LIFECYCLE_LABEL,
NULL AS LIFECYCLE_STAGE_UPDATE_DATE,
NULL AS LIFECYCLE_STAGE_CISCO,
NULL AS LIFECYCLE_STAGE_CISCO_UPDATE_DATE,
NULL AS TUCTSCUSS,

CASE 
    WHEN (T1.TUCKONZS LIKE '%[AA-ZZ ]%' 
          OR T1.TUCKONZS = '' 
          OR T1.TUCKONZS IS NULL 
          OR T1.TUCKONZS = '0000000000') THEN T1.TUCCUSTOR 
    ELSE T1.TUCKONZS 
END AS GROUPKEY_ADJ,

NULL AS DNB_DUNS_NBR,
NULL AS DNB_CONFIDENCE_CODE,
NULL AS  NAME_SCORE,
NULL AS DNB_CITY_SCORE,
NULL AS DNB_STATE_SCORE,
NULL AS DNB_STRNAME_SCORE,
NULL AS DNB_STRNUMB_SCORE,
NULL AS DNB_PHONE_SCORE,
NULL AS DNB_POBOX_SCORE,
T1.TUCACCNTP,
T1.TUCADDRNR,
T1.TUCCITYY,
T1.TUCCOUNTY,
T1.TUCCUSTCS,
T1.TUCCOUNTE,
T1.TUCCUSFCS,
T1.TUCDELINC AS TUCDELINC_TUCCUSTOR,
T1.TUCDBDUNM,
T1.TUCFAXNUM,
T1.TUCINDUSY,
T9."/BIC/TUCINDUSY" AS TUCINDUSY_TEXT,
T1.TUCINDCO1,
T1.TUCINDCO2,
T1.TUCINDCO3,
T1.TUCINDCO4,
T1.TUCINDCO5,
T1.LANGU,
T1.TUCNAMEE,
T1.TUCNAME22,
T1.TUCNAME33,
T1.TUCNIELSD,
T1.TUCPCOMPY,
T1.TUCPHONEE,
T1.TUCPLANTT AS TUCPLANTT_TUCCUSTOR,
T1.TUCPOBOXX,
T1.TUCPOSTAD,
T1.TUCPOSTCX,
T1.TUCPOSTCS,
T1.TUCREGION,
T1.TUCSTREET,
T1.TUCSORTLL,
T1.TUCTAXNUB,
T1.TUCTAXNU2,
T1.TUCUSAGED,
T1.TUCVENDOR,
T1.TUCAUFSD AS TUCAUFSD_TUCCUSTOR,
T1.TUCBBBNR,
T1.TUCBBSNR,
T1.TUCBUBKZ,
T1.TUCEMAILX,
T1.TUDERDATX,
T1.TUCFAKSD AS TUCFAKSD_TUCCUSTOR,
T1.TUCGFORM,
T1.TUCHZUOR,
T1.TUCKATR1,
T1.TUCKATR6,
T1.TUCKDKG3,
T1.TUCKDKG4,
T1.TUCLIFSD AS TUCLIFSD_TUCCUSTOR,
T1.TUCLZONE,
T1.TUCNAME4,
T1.TUCORT2,
T1.TUCPFORT,
T1.TUCSTCEG,
T1.TUCTELBX,
T1.TUCTELFX,
T1.TUCTTXNUM,
T1.TUCVATCOU,
T1.TUCZZGMNR,
T1.TUCSTREE4,
T1.TUCDATLIN,
T1.TUCUMSA1,
T1.TUCUWAERR,
T1.FISCVARNT,
T1.TUCNONVAT,
T1.TUCECG,
T1.TUCKFTBUS,
T1.TUCKFTIND,
T1.TUCBPARTR,
T1.TUCKDKG5,
T1.TUCHUNST,
T1.TUCMETXJD,
T1.TUCELMTET,
T1.TUCSTCD3,
T1.TUCBEGRU AS TUCBEGRU_TUCCUSTOR,
T1.TUCDBA1,
T1.TUCDBA2,
T1.TUCDTAWS,
T1.TUCKATR9,
T1.TUCVENCLN AS TUCVENCLN_TUCCUSTOR,
T1.TUCVENCLS AS TUCVENCLS_TUCCUSTOR,
T3."/BIC/TUCCUSTCC" AS TUCCUSTCC,
T3."/BIC/TUCBUSABD" AS TUCBUSABD,
T3."/BIC/TUCKNRMA" AS TUCKNRMA,
T3."/BIC/TUCCCTRAA" AS TUCCCTRAA_TUCCUSTCC,
T3."/BIC/TUCDELINC" AS TUCDELINC_TUCCUSTCC,
T3."/BIC/TUCEMPLOE" AS TUCEMPLOE,
T3."/BIC/TUCPMNTTS" AS TUCPMNTTS_TUCCUSTCC,
T3."/BIC/TUCPMNTBK" AS TUCPMNTBK,
T3."/BIC/TUCPMTMTL" AS TUCPMTMTL,
T3."/BIC/TUCALTKN"  AS TUCALTKN,
T3."/BIC/TUCBUSAB" AS TUCBUSAB,
T3."/BIC/TUCCRBLB" AS TUCCRBLB,
T3."/BIC/TUCCTLPC" AS TUCCTLPC,
T3."/BIC/TUCDBRTG"	AS 	TUCDBRTG,
T3."/BIC/TUDGMVDTT"	AS 	TUDGMVDTT,
T3."/BIC/TUCGRUPP"	AS 	TUCGRUPP,
T3."/BIC/TUCKNRZE"	AS 	TUCKNRZE,
T3."/BIC/TUCKVERM"	AS 	TUCKVERM,
T3."/BIC/TUCPERKZ"	AS 	TUCPERKZ,
T3."/BIC/TUCSBGRP"	AS 	TUCSBGRP,
T3."/BIC/TUCTOGRU"	AS 	TUCTOGRU,
T3."/BIC/TUDVERDTT"	AS 	TUDVERDTT,
T3."/BIC/TUCVRBKZ"	AS 	TUCVRBKZ,
T3."/BIC/TUCVRSNR"	AS 	TUCVRSNR,
T3."/BIC/TUCVZSKZ"	AS 	TUCVZSKZ,
T3."/BIC/TUCWAKON"	AS 	TUCWAKON,
T3."/BIC/TUCXAUSZ"	AS 	TUCXAUSZ,
T3."/BIC/TUCZWELS"	AS 	TUCZWELS,
T3."/BIC/TUCGUZTE"	AS 	TUCGUZTE,
T3."/BIC/TUCINTADR"	AS 	TUCINTADR,
T3."/BIC/TUKCUCRLI"	AS 	TUKCUCRLI,
T3."/BIC/TUKHORREC"	AS 	TUKHORREC,
T3."/BIC/TUKRECORD" AS 	TUKRECORD_TUCCUSTCC,
T3."/BIC/TUKTOTREC"	AS 	TUKTOTREC,
T3."/BIC/TUKVLIBB"	AS 	TUKVLIBB,
T3."/BIC/TUKWRTAK"	AS 	TUKWRTAK,
T3."/BIC/TUKGENINO"	AS 	TUKGENINO,
T3."/BIC/TUYWAERSX"	AS 	TUYWAERSX,
T3.CURRENCY AS 	CURRENCY_TUCCUSTCC,
T3."/BIC/TUCRCACCT"	AS 	TUCRCACCT,
T3."/BIC/TUCCHRTAS"	AS 	TUCCHRTAS,
T3."/BIC/TUCKNKLI"	AS 	TUCKNKLI,
T3."/BIC/TUCFCFDGP"	AS 	TUCFCFDGP,
T3."/BIC/TUCCRMAN"	AS 	TUCCRMAN,
T3."/BIC/TUCGROREL"	AS 	TUCGROREL,
T3."/BIC/TUCBEGRU" AS 	TUCBEGRU_TUCCUSTCC,
T3."/BIC/TUCZUAWA"	AS 	TUCZUAWA,
T3."/BIC/TUCALTKNA"	AS 	TUCALTKNA,
T3."/BIC/TUCCADUNC"	AS 	TUCCADUNC,
T3."/BIC/TUCLOCKB"	AS 	TUCLOCKB,
T3."/BIC/TUCPRACCT"	AS 	TUCPRACCT,
T3."/BIC/TUDNEXTRV"	AS 	TEDNEXTRV,
T3."/BIC/TUDLASTDN"	AS 	TEDLASTDN,
T3."/BIC/TUCDUNNLL"	AS 	TUCDUNNLL,
T3."/BIC/TUCDUNNBK"	AS 	TUCDUNNBK,
T2.TUCCUSTSS,
T2.TUDLBILDA,
T2.TUCVENCLS AS TUCVENCLS_TUCCUSTSS,
T2.TUCVENCLN AS TUCVENCLN_TUCCUSTSS,
T2.TUCACCNTN,
T2.TUCCUSTCA,
T2.TUCCUSTGP,
T2.TUCCUSTG1,
T2.TUCCUSTG2,
NULL AS TUCCUSTG2_TEXT,
T2.TUCCUSTG3,
T2.TUCCUSTG4,
T2.TUCCUSTG5,
T2.TUCCCTRAA AS TUCCCTRAA_TUCCUSTSS,
T2.TUCDELINC AS TUCDELINC_TUCCUSTSS,
T2.TUCINCOTS,
T2.TUCINCOT2,
T2.TUCPLANTT AS TUCPLANTT_TUCCUSTSS,
T2.TUCPMNTTS AS TUCPMNTTS_TUCCUSTSS,
T2.TUCSALEST,
T2.TUCSALESP,
T2.TUCSALESF,
T2.TUCAKTIV,
T2.TUCAUFSD AS TUCAUFSD_TUCCUSTSS,
T2.TUCCUSCL,
T2.TUCBOKRE,
T2.TUCEDGRP,
T2.TUCEDSTA,
T2.TUCFAKSD AS TUCFAKSD_TUCCUSTSS,
T2.TUCFLLOGO,
T2.TUDFODATE,
T2.TUCGFLAG,
T2.TUCGVFCO,
T2.TUCHIEA01,
T2.TUCHIEA02,
T2.TUCHIEA03,
T2.TUCHIEB01,
T2.TUCHIEB02,
T2.TUCHIEB03,
T2.TUCHIEC01,
T2.TUCHIEC02,
T2.TUCHIEC03,
T2.TUCHIEC04,
T2.TUCHIED01,
T2.TUCHIED02,
T2.TUCHIED03,
T2.TUCHIED04,
T2.TUCHIEE01,
T2.TUCHIEE02,
T2.TUCHIEE03,
T2.TUCHIEE04,
T2.TUCHIEF01,
T2.TUCHIEF02,
T2.TUCHIEF03,
T2.TUCHIEG01,
T2.TUCHIEG02,
T2.TUCHIEG03,
T2.TUCKALKS,
T2.TUCKONDA,
T2.TUCKZAZU,
T2.TUCKZTLF,
T2.TUDLEDORD,
T2.TUCLIFSD AS TUCLIFSD_TUCCUSTSS,
T2.TUDLITORD,
T2.TUDLORDDA,
T2.TUCLPRIO,
T2.TUCPERFK,
T2.TUCPLTYP,
T2.TUCPRAT5,
T2.TUCPRAT6,
T2.TUCPRAT7,
T2.TUDUDATEE,
T2.TUCVERSG,
T2.TUCVSBED,
T2.TUCWECOD,
T2.TUCZPRAT1,
T2.TUCZPRAT2,
T2.TUCZPRAT3,
T2.TUCZPRAT4,
T2.TUCZPRAT5,
T2.TUCZPRAT6,
T2.TUCZZDRBL,
T2.TUCZZPIBL,
T2.TUCKURST,
T2.TUKRECORD AS TUKRECORD_TUCCUSTSS,
T2.CURRENCY AS CURRENCY_TUCCUSTSS,
T2.TUCPODREL,
T2.TUCCUABC,
T2.TUCHPCL,
T2.TUCFRDS,
T2.TUCZPRAT7,
T2.TUCHIEH01,
T2.TUCHIEH02,
T2.TUCHIEH03,
T2.TUCTELCO,
T2.TUCDIGSIG,
T2.TUKPAML,
NULL AS CE_PAM_EUR,
T2.TUDPAMLUU,
T2.TUYLOCCUY,
T2.TUCTCDGRP,
T2.TUCZORPRI,
T2.TUCPVKSM,
T2.TUCINVSOU,
T2.TUCUSEXFL,
T2.TUCFRFWFL,
T2.TUCZPRA12,
T2.TUCZPRA13,
T2.TUCCUSUNV
FROM {{ ref('tuccustor_view') }}  AS T1
JOIN {{ ref('tuccustss_view') }}  AS T2 
  ON T1.TUCCUSTOR = T2.TUCCUSTSS 
  AND T1.SOURSYSTEM = T2.SOURSYSTEM
  AND T2.TUCDISTRN = '00'
  AND T2.TUCDIVISN = '10'

JOIN {{ source('us_cdp_bw_46','TUCCUSTCC') }} AS T3 
  ON T2.TUCCUSTSS = LTRIM(T3."/BIC/TUCCUSTCC") 
  AND T2.SOURSYSTEM = T3.SOURSYSTEM
  AND T2.TUCSALESG = T3."/BIC/TUCCOMPCE"

LEFT JOIN {{ source('us_cdp_bw_46','TUCINDUSY_TXT') }} AS T9  ON T1.TUCINDUSY = T9."/BIC/TUCINDUSY"
  
LEFT JOIN (SELECT DISTINCT TUCSALESG,TNCBPCUST,TNECUSNU 
           FROM  {{ ref('customermaster_base_68') }} ) AS T4 
  ON T1.TUCCUSTOR = T4.TNECUSNU 
  AND T2.TUCCUSTSS = T4.TNCBPCUST 
  AND T2.TUCSALESG = T4.TUCSALESG

--LEFT JOIN PACE.PRG_PACE_LASTPACEFLAG AS T5 
  -- ON T1.TUCCUSTOR = T5.TUCCUSTOR 
  -- AND T2.TUCSALESG = T5.TUCSALESG

--LEFT JOIN EU_DATAPRACTICE.PAM.LAST_SEGMENTATION_WITH_EXCEPTIONS AS T6 
  -- ON T1.SOURSYSTEM = T6.SOURSYSTEM 
  -- AND T1.TUCCUSTOR = T6.TUCCUSTOR 
  -- AND T2.TUCSALESG = T6.TUCSALESG
  
--LEFT JOIN PACE.PRG_PACE_LASTLIFECYCLESTAGE AS T7 
  -- ON T1.TUCCUSTOR = T7.TUCCUSTOR 
  -- AND T3.TUCCOMPCE = T7.TUCCOMPCE
  
--LEFT JOIN PACE.LIFECYCLE AS T7_2 
  -- ON T7.LIFECYCLE_STAGE = T7_2.LIFECYCLE_CODE
  
--LEFT JOIN PACE.PRG_PACE_LASTPACECLUSTER AS T8 
  -- ON T1.TUCCUSTOR = T8.TUCCUSTOR 
  -- AND T2.TUCSALESG = T8.TUCCOMPCE
  
--LEFT JOIN DNB.DNB_MAP_FACT AS T10 
  -- ON T1.TUCCUSTOR = T10.DOC_ID_1 
  -- AND T10.WORKFLOW = 'TDE_CUSTOMERMASTER_RESELLER' 
  -- AND T10.TD_REGION = 'EMEA' 
  -- AND T10.DNB_CONFIDENCE_CODE >= 7
  
--LEFT JOIN (SELECT * FROM 
--(SELECT COMPANY_CODE, RESELLER_ID, GLBL_MFR, LIFECYCLE_VALUE FROM PACE_VENDOR.VENDOR_LAST_LIFECYCLE) AS T
--PIVOT(MAX(LIFECYCLE_VALUE) FOR GLBL_MFR IN ('CISCO')) AS P (COMPANY_CODE, RESELLER_ID, LIFECYCLE_STAGE_CISCO )) AS T11 ON  T1.TUCCUSTOR = T11.RESELLER_ID AND T3.TUCCOMPCE = T11.COMPANY_CODE

--LEFT JOIN (SELECT * FROM 
--(SELECT COMPANY_CODE, RESELLER_ID, GLBL_MFR, T.DB_CREATED_DATE FROM PACE_VENDOR.VENDOR_LAST_LIFECYCLE AS T) AS T
--PIVOT(MAX(DB_CREATED_DATE) FOR GLBL_MFR IN ('CISCO')) AS P (COMPANY_CODE, RESELLER_ID, LIFECYCLE_STAGE_CISCO_UPDATE_DATE )) AS T12 ON  T1.TUCCUSTOR = T12.RESELLER_ID AND T3.TUCCOMPCE = T12.COMPANY_CODE

WHERE 
T1.SOURSYSTEM = 'A3'