{{
    config(
        alias = 'customermaster_base_cis_mapped'

    )
}}
 
select

case 
    when T2.TUCCUSTSS is not NULL 
     and T2.TUCCUSTSS != '' then T2.TUCCUSTSS 
    else NULL 
end as TUCCUSTOR_46,
    
t1.TUCSALESG,
t1.SOURSYSTEM,
t1.OBJVERS,
t1.CIS_CUST_NO,
t1.CIS_CUST_NAME,
t1.LTD_46_CUST_NO,
t1.MCUST_NAME,
t1.INDUSTRY,
t1.POSTAL_CD,
t1.CITY,
t1.ADDRESS,
t1.STATE,
t1.PHONE_NO,
t1.COUNTRY,
t1.DELETION_IND,
t1.CUST_TYPE_DESCR as CUST_TYPE,
T2.TUCHIEA02,
T2.TUCHIEA01,
T2.TUCHIEA03,
T2.TUCHIEB03,
T2.TUCCUSTGP,
T3."/BIC/TUCKONZS" as TUCKONZS,
T3."/BIC/TUCNAMEE" as GROUPKEYNAME,
T3."/BIC/TUCINDUSY" as TUCINDUSY
from "US_DATAPRACTICE"."CDP"."CUSTOMERMASTER_BASE_CIS" as T1

left join TUCCUSTSS as T2
  on T1.TUCSALESG = T2.TUCSALESG
  and T1.LTD_46_CUST_NO = LTRIM(T2.TUCCUSTSS,'0')

left join TUCCUSTOR as T3
  on T2.TUCCUSTSS = T3."/BIC/TUCCUSTOR"