{{
     config(
         alias = 'billing_full',
         materialized = 'table'

     )
 }}

with matl as (
select 
    GLBL_MFR, 
    PROD_FAMILY, 
    PROD_CLASS, 
    PROD_SUBCLASS, 
    MATERIAL_ID, 
    SOURSYSTEM, 
    SALES_ORG, 
    DISTR_CHANNEL
from {{ ref('material_master') }} 
--from US_DATAPRACTICE.CORE.MATERIAL_MASTER
),

cust as (
select distinct     
    cust.tnecusnu as TUCCUSTSS, 
    cust.tncbpcust
--from US_DATAPRACTICE.CDP.CUSTOMERMASTER_BASE_68  cust
from {{ source('us_cdp', 'CUSTOMERMASTER_BASE_68') }}  cust
join (select tnsaleorg,tnecusnu, max(createdon) createdon
      --from US_DATAPRACTICE.CDP.CUSTOMERMASTER_BASE_68 
      from {{ source('us_cdp', 'CUSTOMERMASTER_BASE_68') }} 
      where tnsaleorg = '1001'
      group by tnsaleorg,tnecusnu
      ) as max_cust
  on cust.tnecusnu = max_cust.tnecusnu
  and cust.tnsaleorg = max_cust.tnsaleorg
  and cust.createdon = max_cust.createdon
),

cis_cust_xref as (       
        select xref.*, to_char(cust.mcust_no) mcust_no
        from (
            select to_char(cust_no) cust_no, 
                   xref,  
                   xref_no,
                   ROW_NUMBER() OVER (PARTITION BY xref ORDER BY entry_datetime desc) as rn
                from {{ source('us_cdp_cis_us','DIM_PUB_CUSTOMER_XREF_US') }} a
                --from ANALYTICS.EDW_CIS_US.DIM_PUB_CUSTOMER_XREF_US a
                where xref_type = 'LTD_CUST'                 
                    ) xref
        left join {{ source('us_cdp_cis_us','DIM_PUB_CUSTOMER_INFO_VIEW_US') }} cust
        --left join ANALYTICS.EDW_CIS_US.DIM_PUB_CUSTOMER_INFO_VIEW_US cust
          on xref.cust_no = cust.cust_no
        where rn = 1
                   )

select 
md5(concat('', '', '', '', t1."/BIC/TUCBILLNM", t1."/BIC/TUCBILLIM", t1.SOURSYSTEM, t1.RECORDMODE)) as BILLING_KEY
,md5(t1."/BIC/TUCPROFIR") as PROFIT_CENTER_MASTER_KEY
,md5(concat(t1.SOURSYSTEM, t1."/BIC/TUCSALESG", t1."/BIC/TUCDIVISN", t1."/BIC/TUCDISTRN", t1."/BIC/TUCSOLDTO")) as CUSTOMER_MASTER_KEY
,md5(concat(t1.SOURSYSTEM,t1."/BIC/TUCMATERL", t1."/BIC/TUCSALESG", t1."/BIC/TUCDISTRN")) as MATERIAL_MASTER_KEY
,t1."/BIC/TUCSOLDTO" as RESELLER_ID_46
,NVL(cis_cust_xref.mcust_no, t1."/BIC/TUCSOLDTO") AS RESELLER_ID_COMBINED 
,cust.TNCBPCUST as RESELLER_ID_68
,NULL as IP_CHARGEBACK_DOC_ITEM
,NULL as IP_CHARGEBACK_DOC_NBR
,NULL as IP_CHARGEBACK_LOG_DOC_NBR
,NULL as IP_CHARGEBACK_LOG_TYPE
,t1."/BIC/TUCBILLNM" as BILL_DOC
,t1."/BIC/TUCBILLIM" as BILL_ITEM
,t1.SOURSYSTEM
,t1.RECORDMODE as BW_DELTA_PROCESS 
,NULL AS PROMO_OPTIMIZATIN
,NULL AS CUST_PROJECT_NAME
,NULL AS CUST_REBATE_FLAG
,NULL AS SPECIAL_STOCK
,NULL AS TECH_DATA_AS_A_SERVICE
,t1."/BIC/TUCMATERL" as MATERIAL_ID
,t1."/BIC/TUCSTORNO" as REVERSAL_IND

,CASE
  WHEN t1."/BIC/TUDCHONN" IS NULL OR t1."/BIC/TUDCHONN" = '' OR t1."/BIC/TUDCHONN" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDCHONN", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS LAST_CHANGED_ON

,t1."/BIC/TUCSALEST" as SALES_DISTRICT
,t1."/BIC/TUCBILLTE" as BILL_TYPE
,t1."/BIC/TUCBILLCT" as BILL_CTGRY
,t1."/BIC/TUCCUSTGP" as CUST_GRP
,t1."/BIC/TUCPAYERR" as PAYER 
,t1."/BIC/TUCRTPROO" as PROMOTION
,t1."/BIC/TUCDOCNUR" as SALES_DOC
,t1."/BIC/TUCSORDIX" as SALES_DOC_ITEM 
,t1."/BIC/TUCREBATP" as VOLUME_REBATE_GRP
,t1."/BIC/TUCBATCHH" as BATCH_NBR
,t1."/BIC/TUCEANUPC" as EUROPEAN_ARTICLE_NBR

,CASE
  WHEN t1."/BIC/TUDSERVDE" IS NULL OR t1."/BIC/TUDSERVDE" = '' OR t1."/BIC/TUDSERVDE" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDSERVDE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS SERVICES_RENDERED_DATE

,t1."/BIC/TUCSALESL" as SALES_DEAL

,CASE
  WHEN t1."/BIC/TUDTRANSE" IS NULL OR t1."/BIC/TUDTRANSE" = '' OR t1."/BIC/TUDTRANSE" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDTRANSE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS CONVERSION_DATE

,t1."/BIC/TUCPRICOL" as CUST_PRICING_COLUMN
,t1."/BIC/TUCCUSTG1" as PROFILE_COLUMN
,t1."/BIC/TUCCUSTG2" as CUST_GRP_2
,t1."/BIC/TUCCUSTG3" as FREIGHT_COLUMN
,t1."/BIC/TUCCUSTG4" as SPECIAL_HANDLING_MD
,t1."/BIC/TUCCUSTG5" as ORDER_FULFILLMENT
,t1."/BIC/TUCSTORLC" as STORAGE_LOCATION
,t1."/BIC/TUCMATEND" as MATERIAL_ENTERED
,t1."/BIC/TUCMATLG1" as BUSINESS_MANAGER
,t1."/BIC/TUCMATLG2" as DIVISION_MANAGER
,t1."/BIC/TUCMATLG3" as DIRECTOR  
,t1."/BIC/TUCMATLG4" as REPAIR_TIME_DAYS
,t1."/BIC/TUCMATLG5" as INVESTIGATION_RESULT
,t1."/BIC/TUCBILLTY" as BILL_TO_PARTY
,t1."/BIC/TUCSHIPTO" as SHIP_TO_PARTY
,t1."/BIC/TUCITMTYE" as ITEM_TYPE
,t1."/BIC/TUCPROFIR" as PROFIT_CENTER
,t1."/BIC/TUCPRODHR" as PROD_HRCHY
,t1."/BIC/TUCPROVGP" as COMMISSION_GRP

,CASE
  WHEN t1."/BIC/TUDPRICEE" IS NULL OR t1."/BIC/TUDPRICEE" = '' OR t1."/BIC/TUDPRICEE" = '00000000'   THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDPRICEE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS PRICING_EXCHANGE_RATE_DATE

,t1."/BIC/TUCITEMCG" as SALES_DOC_ITEM_CAT
,t1."/BIC/TUCSALESY" as SALES_EMPLOYEE

,CASE
  WHEN t1."/BIC/TUDSTATDE" IS NULL OR t1."/BIC/TUDSTATDE" = '' OR t1."/BIC/TUDSTATDE" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDSTATDE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS STATS_DATE

,CASE
 WHEN t1."/BIC/TUDSTUPDE" IS NULL OR t1."/BIC/TUDSTUPDE" = '' OR t1."/BIC/TUDSTUPDE" = '00000000'  THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDSTUPDE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS UPDATE_STATS_DATE

,t1."/BIC/TUCREFERC" as DOC_NBR_OF_REF_DOC 
,t1."/BIC/TUCXABLN" as  SAP_INTERNAL_DELIVERY_NBR
,t1."/BIC/TUCREFERM" as ITEM_NBR_OF_REF_ITEM 
,t1."/BIC/TUCSALESF" as SALES_OFFICE
,t1."/BIC/TUCSHIPPT" as SHIPPING_POINT
,t1."/BIC/TUCPLANTT" as PLANT
,t1."/BIC/TUCRATETE" as EXCHANGE_RATE_TYPE
,t1."/BIC/TUCDOCCAG" as SALES_DOC_CAT
,t1."/BIC/TUCCOAREA" as CONTROLLING_AREA
,t1."/BIC/TUCCOSTCR" as COST_CENTER
,t1."/BIC/TUCMATLGP" as MATERIAL_GRP
,t1."/BIC/TUCDIVHED" as DIVISION_ORDER_HEADER
,t1."/BIC/TUCSALESP" as SALES_GRP
,t1."/BIC/TUCBWAPPM" as APPLICATION_COMPONENT
,t1."/BIC/TUCPROCEY" as BW_TRANSACTION_KEY
,t1."/BIC/TUCCUSTH1" as SUPER_SALES_AREA
,t1."/BIC/TUCCUSTH2" as SALES_AREA
,t1."/BIC/TUCCUSTH3" as SALES_EXECUTIVE
,t1."/BIC/TUCHIEZ4" as CUST_HRCHY_LVL_4
,t1."/BIC/TUCHIEZ5" as CUST_HRCHY_LVL_5
,t1."/BIC/TUCKTGRM" as ACCNT_ASSIGN_GRP_MATERIAL
,t1."/BIC/TUCDNDRE" as DND_REASON
,t1."/BIC/TUCACCNTN" as CUST_ACCNT_ASGMT_GRP
,t1."/BIC/TUCSHIPCD" as SHIPPING_CONDS
,t1."/BIC/TUCREFDOO" as REF_DOC_NBR
,t1."/BIC/TUCFAREG" as RULE_IN_BILL_PLAN
,t1."/BIC/TUCARKTX" as SALES_ORDER_ITEM_SHORT
,t1."/BIC/TUCMPROK" as MANUAL_PRICE_CHANGE
,t1."/BIC/TUCPRVDOG" as PRECEDING_DOC_CAT
,t1."/BIC/TUCZZERMA" as ERMA_NBR

,CASE
  WHEN t1."/BIC/TUDZZDATE" IS NULL OR t1."/BIC/TUDZZDATE" = '' OR t1."/BIC/TUDZZDATE" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDZZDATE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS END_USER_DATE

,t1."/BIC/TUCZZINV" as END_USER_INVOICE_NBR
,t1."/BIC/TUCZZACC" as ACCESSORIES
,NULL AS WARRANTY_IND
,t1."/BIC/TUCBNAME" as NAME_OF_ORDERER
,t1."/BIC/TUCKDMAT" as CUST_PART_NBR
,t1."/BIC/TUCENCUST" as END_CUST_NBR
,t1."/BIC/TUCFSCQTE" as FREE_PROJECT_NBR
,t1."/BIC/TUCAGRNOT" as DRM_AGREEMENT_NO_TEX
,t1."/BIC/TUCKDKG2"  as PA_SF_REASON_CODE
,t1."/BIC/TUCIHREZ"  as CUST_VENDOR_INTERNAL_REF
,t1."/BIC/TUCBSTKDE" as SHIP_TO_PARTY_ORDER_NBR
,t1."/BIC/TUCPMNTTS" as PAYMENT_TERMS
,t1."/BIC/TUCNEGFEM" as NEGATIVE_FEM_FLAG
,t1."/BIC/TUCZZPCOD" as PP_CODE
,t1."/BIC/TUCZZSPON" as SALES_PROJECT_OWNER
,t1."/BIC/TUCCREATY" as CREATED_BY
,t1."/BIC/TUCARCH"   as ARCHIVE_FLAG
,t1."/BIC/TUKEXRATX" as EXCHANGE_RATE_FI_POSTINGS
,t1."/BIC/TUKREBATS" as REBATE_BASIS_1
,t1."/BIC/TUKGRSWGL" as GROSS_WEIGHT
,t1."/BIC/TUKINVQTY" as BILLED_QTY_SALES_UNITS
,t1."/BIC/TUKBILLQY" as BILL_QTY_BASE_UNITS
,t1."/BIC/TUKORIQTY" as BILLED_QTY_ORIGINAL
,t1."/BIC/TUKEXCHGE" as EXCHANGE_RATE_PRICING_STATS
,t1."/BIC/TUKEXRATC" as EXACT_EXCHANGE_RATE_FI_POSTING
,t1."/BIC/TUKREQQTY" as REQUIRED_QTY_MAT_MNGMT 
,t1."/BIC/TUKTAXAMT" as TAX_AMOUNT_DC
,t1."/BIC/TUKNETWGL" as NET_WEIGHT
,t1."/BIC/TUKCSHDSS" as AMOUNT_CASH_DISCOUNT_DC
,t1."/BIC/TUKSCALEY" as SCALE_QTY_BASE_UNIT
,t1."/BIC/TUKDENOMR" as DIVISOR_SALES_QTY_TO_SKU
,t1."/BIC/TUKNUMERR" as FACTOR_SALES_QTY_TO_SKU
,t1."/BIC/TUKVOLUML" as VOLUME_DELIVERED 
,t1."/BIC/TUKCOSTT" as  COST_DC
,t1."/BIC/TUKNOINVT" as NBR_BILL_ITEMS
,t1."/BIC/TUKSUBTO1" as COND_SUBTOTAL_1
,t1."/BIC/TUKSUBTO2" as SYSTEM_SELL_PRICE_DC
,t1."/BIC/TUKSUBTO3" as PROPOSED_FREIGHT_DOC
,t1."/BIC/TUKSUBTO4" as COND_SUBTOTAL_4 
,t1."/BIC/TUKSUBTO5" as FRONT_END_PROFIT_DOC
,t1."/BIC/TUKSUBTO6" as COND_SUBTOTAL_6
,t1."/BIC/TUKNETVAV" as NET_VALUE_BILL_ITEM_
,t1."/BIC/TUKEXCHGT" as EXCHANGE_RATE_STATS
,t1."/BIC/TUKGROSSL" as GROSS_WEIGHT_SD_DC 
,t1."/BIC/TUYDOCCUY" as DOC_CURR
,t1."/BIC/TUUUNITOT" as WEIGHT_UNIT
,t1."/BIC/TUUSALEST" as SALES_UNIT
,t1."/BIC/TUUBASEUM" as BASE_UNIT
,t1."/BIC/TUUVOLUMT" as VOLUME_UNIT
,t1."/BIC/TUYSTATCR" as STATS_CUR
,t1."/BIC/TUYLOCCUY" as LOC_CUR

,CASE
  WHEN t1."/BIC/TUDREQDAE" IS NULL OR t1."/BIC/TUDREQDAE" = '' OR t1."/BIC/TUDREQDAE" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDREQDAE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS REQ_DELIVERY_DATE

,t1."/BIC/TUCDOCTYX" as SALES_DOC_TYPE
,t1."/BIC/TUCOERNAM" as SO_ITEM_CREATED_BY
,t1."/BIC/TUCBSARK" as METHOD_ORDER_TAKING
,t1."/BIC/TUKPRCLP" as LP_LIST_PRICE
,t1."/BIC/TUYKONWAA" as RATE_UNIT_CUR_OR_PERC
,t1."/BIC/TUKCONDPC" as COND_RATE_PURCH_PRICE
,t1."/BIC/TUYCURRPC" as CUR_KEY_PURCH_COST
,t1."/BIC/TUKCONDAC" as COND_RATE_ADJ_COST
,t1."/BIC/TUYCURRAC" as CUR_KEY_ADJ_COST
,t1."/BIC/TUKSUB1L" as SELL_PRICE_LC
,t1."/BIC/TUKSUB2L" as SYSTEM_SELL_PRICE_LC
,t1."/BIC/TUKSUB3L" as PROPOSED_FREIGHT_LC
,t1."/BIC/TUKSUB4L" as ACTUAL_FREIGHT_LC
,t1."/BIC/TUKSUB5L" as FRONT_END_PROFIT_LC
,t1."/BIC/TUKSUB6L" as NET_SALES_PROFIT_LC
,t1."/BIC/TUKNTVLL" as NET_VALUE_LC
,t1."/BIC/TUKCOSTL" as COST_LC
,t1."/BIC/TUKSUB1E" as SELL_PRICE_EUR
,t1."/BIC/TUKSUB2E" as SYSTEM_SELL_PRICE_EUR
,t1."/BIC/TUKSUB3E" as PROPOSED_FREIGHT_EUR
,t1."/BIC/TUKSUB4E" as ACTUAL_FREIGHT_EUR
,t1."/BIC/TUKSUB5E" as FRONT_END_PROFIT_EUR
,t1."/BIC/TUKSUB6E" as NET_SALES_PROFIT_EUR
,t1."/BIC/TUKNTVLE" as NET_VALUE_EUR
,t1."/BIC/TUKCOSTE" as COST_EUR
,t1."/BIC/TUCSHIPPP" as SHIPPING_TYPE
,t1."/BIC/TUCDIVISN" as DIVISION
,'US01' as COMPANY_CODE
,'US01' as SALES_ORG
,t1."/BIC/TUCDISTRN" as DISTR_CHANNEL
,t1."/BIC/TUCUSAGED" as USAGE_IND_MATERIAL
,t1."/BIC/TUCCCTRAA" as CREDIT_CONTROL_AREA
,t1."/BIC/TUCSBGRP" as CREDIT_MGMT_REPS_GRP
,t1."/BIC/TUCPRICON" as PRICING_COND
,t1."/BIC/TUCKONDM" as MATERIAL_PRICING_GRP
,t1."/BIC/TUCFKSTO" as BILL_DOC_IS_CANCELLED
,t1."/BIC/TUCSFAKN" as CANCELLED_BILL_DOC_NBR
,t1."/BIC/TUCYYWI12" as SND_FLAG
,t1."/BIC/TUKSDCNT" as PRICING_COND_COUNTER
,t1."/BIC/TUCBSTKD" as CUST_PO_NBR
,t1."/BIC/TUCSOLDTO" as RESELLER_ID
,t1."/BIC/TUCMATPLT" as MATERIAL_PLANT
,t1."/BIC/TUCMATSAS" as MATERIAL_SALES
,t1."/BIC/TUCMATSTC" as MATERIAL_STORAGE_LOC
,t1."/BIC/TUCCUSTCC" as RESELLER_ID_CC
,t1."/BIC/TUCCUSTSS" as RESELLER_ID_SS
,t1."/BIC/TUCADRZE" as  END_USER_DETAIL_INFO
,t1."/BIC/TUCADRSH" as SHIP_TO_DETAIL_INFO
,t1."/BIC/TUCABRVW" as USAGE_IND_HEADER
,t1."/BIC/TUCPODREL" as POD_RELEVANT
,t1."/BIC/TUCRECASE" as REGIONAL_SALES_ITEM
,t1."/BIC/TUCFLAGTP" as SALES_ITEM_FLAG

,CASE
  WHEN t1."/BIC/TUDCREATN" IS NULL OR t1."/BIC/TUDCREATN" = '' OR t1."/BIC/TUDCREATN" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDCREATN", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS CREATION_DATE

,CASE
  WHEN t1."/BIC/TUDLOADAT" IS NULL OR t1."/BIC/TUDLOADAT" = '' OR t1."/BIC/TUDLOADAT" = '00000000'  THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDLOADAT", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS LOADING_DATE_INTO_BW

,t1."/BIC/TUKSB10" as BUMPED_PRICE_DOC
,t1."/BIC/TUKSB10L" as BUMPED_PRICE_LC
,t1."/BIC/TUKSB15" as SND_CUST_ALLOW
,t1."/BIC/TUKSB15L" as SND_CUST_ALLOW_LC
,t1."/BIC/TUKSB18" as KIT_SND_CUST_ALLOW
,t1."/BIC/TUKSB18L" as KIT_SND_CUST_ALLOW_LC
,t1."/BIC/TUKSB24" as SYS_NSP_DOC_PRICE
,t1."/BIC/TUKSB24L" as SYS_NSP_CUST_PRICE_LC
,t1."/BIC/TUKSB25" as NSP_DOC_PRICE
,t1."/BIC/TUKSB25L" as NSP_LC
,t1."/BIC/TUKSB25E" as NSP_EUR
,t1."/BIC/TUKSB27" as SND_VENDOR_ALLOW_DC
,t1."/BIC/TUKSB27L" as SND_VENDOR_ALLOW_LC
,t1."/BIC/TUKSB28" as PC_PRICE
,t1."/BIC/TUKSB28L" as PC_PRICE_LC
,t1."/BIC/TUCMANPRI" as MAN_PRICING_IND
,t1."/BIC/TUKSB13" as BUMP_VALUE_DOC
,t1."/BIC/TUKSB13L" as BUMP_VALUE_LC 
,t1."/BIC/TUKSB37" as GOV_FEE_DOC
,t1."/BIC/TUKSB37L" as GOV_FEE_LC
,t1."/BIC/TUKSB39" as VELOCITY_DOC
,t1."/BIC/TUKSB39L" as VELOCITY_LC 
,t1."/BIC/TUKSB40" as INTOUCH_DISCOUNT_DOC
,t1."/BIC/TUKSB40L" as INTOUCH_DISCOUNT_LC
,t1."/BIC/TUKSB44" as PC_PRICE_VENDOR_CUR
,t1."/BIC/TUYCURRVE" as VENDORS_CUR
,t1."/BIC/TUKSB45L" as END_CUST_PRICE_REF_LC
,t1."/BIC/TUKSB46" as AC_PRICE
,t1."/BIC/TUKSB46L" as AC_PRICE_LC
,t1."/BIC/TUKSB47" as TOTAL_CA_ON_AC_KIT_COMP
,t1."/BIC/TUKSB47L" as TOTAL_CA_ON_AC_KIT_COMP_LC
,t1."/BIC/TUKSB48" as TOTAL_CA_ON_AC_KIT_HEADER
,t1."/BIC/TUKSB48L" as TOTAL_CA_ON_AC_KIT_HEADER_LC
,t1."/BIC/TUKSB49" as SALES_ADJ_PROFIT
,t1."/BIC/TUKSB49L" as SALES_ADJ_PROFIT_LC
,t1."/BIC/TUKSB55" as WEEE_GOV_FEE
,t1."/BIC/TUKSB55L" as WEEE_GOV_FEE_LC
,t1."/BIC/TUKSB56" as FUNCTIONAL_DISCOUNT
,t1."/BIC/TUKSB56L" as FUNCTIONAL_DISCOUNT_LC

,CASE
  WHEN t1."/BIC/TUDOERDAT" IS NULL OR t1."/BIC/TUDOERDAT" = ''  OR t1."/BIC/TUDOERDAT" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDLOADAT", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS SALES_ORDER_DATE

,t1."/BIC/TUCWRRNTY" as WARRANTY
,t1."/BIC/TUCEDIEND" as EDI_ENDCUST_INVOICE 
,NULL AS UTC_TIME_STAMP
,t1."/BIC/TUCADRSO" as SOLD_TO_PARTY_DETAIL
,t1."/BIC/TUKSB70" as MIN_ORDER_SURCHARGE_DC
,t1."/BIC/TUKSB70L" as MIN_ORDER_SURCHARGE_LC
,t1."/BIC/TUKAVELL" as ACTUAL_VEITY_LC
,t1."/BIC/TUKSB91" as ADD_FREIGHT_TOLLS_DC
,t1."/BIC/TUKSB91L" as ADD_FREIGHT_TOLLS_LC 

,CASE
  WHEN t1."/BIC/TUDARCHH"IS NULL OR t1."/BIC/TUDARCHH" = '' OR t1."/BIC/TUDARCHH" = '00000000'  THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDARCHH", 'YYYYMMDD'), 'YYYY-MM-DD'))
  END AS ARCHIVING_DATE

,t1."/BIC/TUKSB44SO" AS PC_PRICE_VENDOR_CUR_SO 

,CASE
  WHEN t1."/BIC/TUDPRCSOO" IS NULL OR t1."/BIC/TUDPRCSOO" = '' OR t1."/BIC/TUDPRCSOO" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDPRCSOO", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS PRICING_DATE_SO 
 
,t1."/BIC/TUKSB80" as BEM_2_DOC
,t1."/BIC/TUKSB80L" as BEM_2_LC
,t1."/BIC/TUKSB81L" as FREIGHT_COSTS_LC
,t1."/BIC/TUKSB81" as FREIGHT_COSTS_DOC
,t1."/BIC/TUKSB82" as NET_FREIGHT_DOC
,t1."/BIC/TUKSB82L" as NET_FREIGHT_LC
,t1."/BIC/TUKSB83" as LOGISTIC_COSTS_DOC
,t1."/BIC/TUKSB83L" as LOGISTIC_COSTS_LC
,t1."/BIC/TUKSB84" as FINANCIAL_COSTS_DOC
,t1."/BIC/TUKSB84L" as FINANCIAL_COSTS_LC 
,t1."/BIC/TUKSB85" as MIN_POM_DOC
,t1."/BIC/TUKSB85L" as MIN_POM_LC
,t1."/BIC/TUKSB86" as POCKET_MARGIN_DOC
,t1."/BIC/TUKSB86L" as POCKET_MARGIN_LC
,t1."/BIC/TUKSB89" as DIESEL_SURCHARGE_DOC
,t1."/BIC/TUKSB89L" as DIESEL_SURCHARGE_LC
,t1."/BIC/TUKSB92" as ADD_POM_FACTOR_DOC
,t1."/BIC/TUKSB92L" as ADD_POM_FACTOR_LC
,t1."/BIC/TUKSB93" as COND_ZRET_ASM_BUMP_DOC
,t1."/BIC/TUKSB93L" as COND_ZRET_ASM_BUMP_LC
,t1."/BIC/TUKSB94" as FREIGHT_BUMP_ZZ78_DOC
,t1."/BIC/TUKSB94L" as FREIGHT_BUMP_ZZ78_LC

,CASE
  WHEN t1."/BIC/TUDCODTT" IS NULL OR t1."/BIC/TUDCODTT" = ''  OR t1."/BIC/TUDCODTT" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDCODTT", 'YYYYMMDD'), 'YYYY-MM-DD'))
  END AS COND_DATE
,NULL as COPY_RIGHT_TAX_ZZG9
,t1."/BIC/TUKSB87L" as COPY_RIGHT_TAX_ZZG9_LC

,CASE
  WHEN t1."/BIC/TUDCODTSO" IS NULL OR t1."/BIC/TUDCODTSO" = '' OR t1."/BIC/TUDCODTSO" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDCODTSO", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS COND_DATE_SO

,t1."/BIC/TUKSB97" as COND_ZZG6_GOV_FEE_DOC
,t1."/BIC/TUKSB97L" as COND_ZZG6_GOV_FEE_LC
,t1."/BIC/TUKSB98" as COND_ZZ94_RETAIL_DISCOUNT_DOC
,t1."/BIC/TUKSB98L" as COND_ZZ94_RETAIL_DISCOUNT_LC
,t1."/BIC/TUKSB99" as COND_ZEDI_EDI1_PRICE_DIFF
,t1."/BIC/TUKSB99L" as COND_ZEDI_EDI1_PRICE_DIFF_LC
,t1."/BIC/TUKZWI02" as COND_ZZ74_ENV_FEE_HEADER
,t1."/BIC/TUKZWI02L" as COND_ZZ74_ENV_FEE_HEADER_LC 
,t1."/BIC/TUCSTCEG" as VAT_REGISTRATION_NBR
,t1."/BIC/TUCOWNVAT" as TD_VAT_REGISTRATION_NBR
,t1."/BIC/TUCTAXK1" as ALT_TAX_CLASS
,t1."/BIC/TUCTAXM1" as TAX_CLASS
,t1."/BIC/TUKZWI03" as PROPOSED_MIN_QTY_SURCHARGE
,t1."/BIC/TUKZWI04" as ACTUAL_MIN_QTY_SURCHARGE
,t1."/BIC/TUKZWI03L" as PROPOSED_MIN_QTY_SURCHARGE_LC
,t1."/BIC/TUKZWI04L" as ACTUAL_MIN_QTY_SURCHARGE_LC
,t1."/BIC/TUCSSPCN" as SPEC_STOCKPARTN
,t1."/BIC/TUCSSPID" as SPEC_STOCKPART_ID
,t1."/BIC/TUCLPRIOX" as DELIVERY_PRIO
,t1."/BIC/TUCMATER" as MATERIAL_TIME_DEPEND
,t1."/BIC/TUCMATPLA" as MATERIAL_PLANT_TIME_DEPEND
,t1."/BIC/TUCMATSAL" as MATERIAL_SALES_TIME_DEPEND
,t1."/BIC/TUCUSALES" as CUST_SALES_TIME_DEPEND
,t1."/BIC/TUCIPLANT" as INITIAL_PLANT
,t1."/BIC/TUCEXPORT" as  EXPORT_FLAG
,t1."/BIC/TUCORDBC" as ORDER_BUCKET_CODE
,t1."/BIC/TUCORDTYP" as BUSINESS_ORDER_TYPE
,t1."/BIC/TUCORDLVL" as BUSINESS_ORDER_LVL
,t1."/BIC/TUKWI05L" as  BASIS_FREIGHT_LC 
,t1."/BIC/TUKWI06L" as WASHINGTON_STATE_FEE_LC
,t1."/BIC/TUKWI07L" as FRONT_END_MARGIN_AC_LC
,t1."/BIC/TUKWI08L" as NET_SALES_MARGIN_AC_LC
,t1."/BIC/TUKWI09L" as SALES_ADJ_MARGIN_AC_LC
,t1."/BIC/TUKWI10L" as POCKET_MARGIN_AC_LC
,t1."/BIC/TUKWI11L" as SELF_FOUNDED_PROMO_LC
,t1."/BIC/TUKZWI5" as BASIS_FREIGHT_DOC
,t1."/BIC/TUKZWI6" as WASHINGTON_STATE_FEE_DOC
,t1."/BIC/TUKZWI7" as FRONT_END_MARGIN_AC_DOC
,t1."/BIC/TUKZWI8" as NET_SALES_MARGIN_AC_DOC
,t1."/BIC/TUKZWI9" as SALES_ADJ_MARGIN_AC_DOC 
,t1."/BIC/TUKZWI10" as POCKET_MARGIN_AC_DOC
,t1."/BIC/TUKZWI11" as SELF_FOUNDED_PROMO_DOC
,t1."/BIC/TUCRPLNR" as NBR_PAYMENT_CARD_PLAN
,t1."/BIC/TUCOFZONE" as OUT_ZONE_FLAG
,t1."/BIC/TUKYB21" as GPMM_MANUAL_PRICE
,t1."/BIC/TUKEVPCVC" as EXTENDED_VENDOR_PURCH_COST_VC
,t1."/BIC/TUKEVPCLC" as EXTENDED_VENDOR_PURCH_COST_LC
,t1."/BIC/TUKSB44L" as PC_PRICE_LC_2
,t1."/BIC/TUKEVPCDC" as EXTENDED_VENDOR_PURCH_COST_DC
,t1."/BIC/TUKSB44D" as PC_PRICE_DC 
,t1."/BIC/TUKSB90L" as VENDOR_REBATES_LC
,t1."/BIC/TUKSB90" as VENDOR_REBATES
,t1."/BIC/TUCZVSBED" as LINE_LVL_SHIP_COND
,t1."/BIC/TUCADRRE" as BILL_TO_DETAIL_INFO
,t1."/BIC/TUCKUNZE" as CUST_DETAILS_INFO
,t1."/BIC/TUCKNUMV" as NBR_DOC_COND
,t1."/BIC/TUKZWI4" as SND_RED_AC_DOC
,t1."/BIC/TUKWI04L" as SND_RED_AC_ZZKZWI4_LC
,t1."/BIC/TUCHORFF" as HRZN_FRA2_FLAG
,t1."/BIC/TUKHORFV" as FREIGHT_ADDER_VALUE_LC
,t1."/BIC/TUCHORIF" as IBU_FLAG
,t1."/BIC/TUKHORIV" as IBU_ADDER_VALUE_LC
,t1."/BIC/TUCHORRF" as ROYALTY_ADDER_FLAG
,t1."/BIC/TUKHORRV" as ROYALTY_ADDER_VALUE 
,t1."/BIC/TUCZOA1" as CUSTOM_FLAG
,t1."/BIC/TUKZOR1V" as CUSTOME_VALUE_LC
,t1."/BIC/TUYOYCURR" as ROYALTY_CUR

,CASE
  WHEN t1."/BIC/TUDORGDAT" IS NULL OR t1."/BIC/TUDORGDAT" = '' OR t1."/BIC/TUDORGDAT" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDORGDAT", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS  ORIGINAL_BILL_DATE

,t1."/BIC/TUCVENDOX" as FIXED_VENDOR_SOURCE_LIST
,t1."/BIC/TUCCAMO" as  CALENDAR_MONTH
,t1."/BIC/TUCSCAQR" as FISCAL_QUARTER
,t1."/BIC/TUCUEPOS" as HIGH_LVL_ITEM_SO
,t1."/BIC/TUCSCAQTR" as CALENDAR_QUARTER
,t1."/BIC/TUCBBPPAO" as HIGHER_LVL_DOC_ITEM_NBR
,t1."/BIC/TUKYAH3" as BUMP_VOLUME_REB_VAL
,t1."/BIC/TUKYAH5" as BUMP_EXCL_VOL_REB
,t1."/BIC/TUKYCK1" as CUST_REBATE_VALUE
,t1."/BIC/TUKYCK2" as CUST_REBATE_EXCL
,t1."/BIC/TUKYCK3" as CUST_REBATE_MDF
,t1."/BIC/TUKYCK4" as CUST_REBATE_EXCL_MDF
,t1."/BIC/TUTCREATE" as TIME_CREATED
,t1."/BIC/TUKYAH2" as BUMP_VOLUME_REB_PERC
,t1."/BIC/TUKYAH4" as BUMP_EXCL_VOL_REB_PERC
,t1."/BIC/TUKTRB" as TOTAL_REBATE_BUMP
,t1."/BIC/TUKTCRB" as TOTAL_CUST_REBATE
,t1."/BIC/TUCBUNID" as BUNDLE_ID 
,t1."/BIC/TUKWI23" as BUMPED_BEST_PRICE_DOC
,t1."/BIC/TUKWI23L" as BUMPED_BEST_PRICE_LC 
,t1."/BIC/TUCREBIND" as VENDOR_PROGRAM
,t1."/BIC/TUKDAYSIN" as DAYS_TO_INVOICE
,t1."/BIC/TUCPEXFLG" as PRICING_EXCEPTION_FLAG

,CASE
  WHEN t1."/BIC/TUDPOSRDT" IS NULL OR t1."/BIC/TUDPOSRDT" = ''  OR t1."/BIC/TUDPOSRDT" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDPOSRDT", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS  POS_REPORTING_DATE

,t1."/BIC/TUCDAYSIN" as DAYS_TO_INVOICE_2
,t1."/BIC/TUCSSOURC" as SERVICES_SOURCING
,t1."/BIC/TUCSTECHN" as SERVICES_TECHNOLOGY
,t1."/BIC/TUCDNDRES" as DND_REASON_NON_EMEA
,t1."/BIC/TUKFXFEMV" as FOREX_CORRECTED_FEM
,t1."/BIC/TUKFEMVL" as FOREX_CORRECTED_FEP_LC
,t1."/BIC/TUKFXNSMV" as FOREX_CORRECTED_NSM
,t1."/BIC/TUKNSMVL" as FOREX_CORRECTED_NSP_LC
,t1."/BIC/TUKFXSAMV" as FOREX_CORRECTED_SAM
,t1."/BIC/TUKSAMVL" as FOREX_CORRECTED_SAP_LC
,t1."/BIC/TUKFXPOMV" as FOREX_CORRECTED_POM
,t1."/BIC/TUKPOMVL" as FOREX_CORRECTED_POP_LC
,t1."/BIC/TUCKNKLI" as CUSTS_ACCNT_NBR_CL_REF
,t1."/BIC/TUCFXCFL" as UPDATE_FLAG
,t1."/BIC/TUKYZWI05" as FLOORPLAN_SPONSORED_DOC
,t1."/BIC/TUKYI05L" as FLOORPLAN_SPONSORED_LC
,t1."/BIC/TUKYZWI06" as MANUAL_GOV_FEE_DOC
,t1."/BIC/TUKYI06L" as MANUAL_GOV_FEE_LC
,t1."/BIC/TUKZACITV" as AC_PLUS_INS_TAX_VALUE
,t1."/BIC/TUKZACRCV" as AC_PLUS_RESELLER_COMMISSION 
,t1."/BIC/TUKZACVCV" as AC_PLUS_VENDOR_COMMISSION
,t1."/BIC/TUCZACVAN" as AC_PLUS_TD_VENDOR_REBATE
,t1."/BIC/TUCZACRAN" as AC_PLUS_TD_RESELLER_REBATE
,t1."/BIC/TUCZACVRF" as AC_PLUS_VENDOR_REBATE_REF
,t1."/BIC/TUCINSURS" as INS_SUPPLIER
,t1."/BIC/TUKZACITL" as AC_PLUS_INS_TAX_VALUE_LC
,t1."/BIC/TUKZACRCL" as AC_PLUS_RESELLER_COMMISSION_LC
,t1."/BIC/TUKZACVCL" as AC_PLUS_VENDOR_COMMISSION_LC
,t1."/BIC/TUCGRKOR" as DELIVERY_GRP
,t1."/BIC/TUKZACITP" as AC_PLUS_INS_PREMIUM_TAX_PERC
,t1."/BIC/TUCEUIVDM" as END_USER_INFO
,t1."/BIC/TUKTDMMOI" as TDM_MDF_ON_INVOICE
,t1."/BIC/TUKMMOIL" as TDM_MDF_ON_INVOICE_LC
,t1."/BIC/TUKZTDMHW" as TDM_HW_SUBSIDY
,t1."/BIC/TUKZTDML" as TDM_HW_SUBSIDY_LC
,t1."/BIC/TUKORSEP" as ORIGINAL_SELL_PRICE_
,t1."/BIC/TUKOCOSL" as ORIGINAL_COST_SUBSCR_LC
,t1."/BIC/TUKYYWI72" as SUBTOTAL_GOV_FEES
,t1."/BIC/TUKWI72L" as SUBTOTAL_GOV_FEES_LC
,t1."/BIC/TUKKZWI1" as SND_BASE_DP_RATE
,t1."/BIC/TUKZWI1L" as SND_BASE_DP_RATE_LC
,t1."/BIC/TUKKZWI28" as RED_FEM_PERC_YAN0
,t1."/BIC/TUKKZWI29" as RED_FEM_USD_YAN0
,t1."/BIC/TUKKZWI30" as MINMARG_PERC_YAPB
,t1."/BIC/TUKKZWI31" as MINMARG_USD_YAPB
,t1."/BIC/TUKWI28L" as RED_FEM_PERC_YAN0_LC
,t1."/BIC/TUKWI29L" as RED_FEM_USD_YAN0_LC
,t1."/BIC/TUKWI30L" as MINMARG_PERC_YAPB_LC
,t1."/BIC/TUKWI31L" as MINMARG_USD_YAPB_LC
,t1."/BIC/TUKWI32L" as WEB_DISCOUNT_VALUE_LC
,t1."/BIC/TUKKZWI32" as WEB_DISCOUNT_VALUE
,t1."/BIC/TUKTAXAL" as TAX_AMOUNT_LC
,t1."/BIC/TUCVOUCHN" as VOUCHER_NBR
,t1."/BIC/TUCVVENID" as VOUCHER_VENDOR_ID
,t1."/BIC/TUKYI07L" as VOUCHER_VALUE_LC
,t1."/BIC/TUKYZWI07" as VOUCHER_VALUE_DOC
,t1."/BIC/TUCLIEOT" as LINE_ORDER_TYPE
,t1."/BIC/TUCORDC" as ORDER_CONSOLIDATION
,t1."/BIC/TUCCFSTH" as CHEM_FEE_STOCK_HOLDER
,t1."/BIC/TUCSOBKZ" as SPECIAL_STOCK_IND
,t1."/BIC/TUKBTOCV" as BTO_CUM_VALUE_DOC
,t1."/BIC/TUKKZWI34" as BAD_BOX_ALLOW_DC
,t1."/BIC/TUCBTOID" as BTO_ID 
,t1."/BIC/TUCIKYC2" as INVENTORY_KEY_SALES
,t1."/BIC/TUCMATLTE" as MATERIAL_TYPE 
,t1."/BIC/TUKWI34L" as BAD_BOX_ALLOW_LC
,t1."/BIC/TUKBTOCVL" as BTO_CUM_VALUE_LC 
,NULL AS SBU_HRCHY_L1_OLD

,CASE
  WHEN t1."/BIC/TUCTCDAYS" IS NULL OR t1."/BIC/TUCTCDAYS" = '' OR t1."/BIC/TUCTCDAYS" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUCTCDAYS", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS CALENDAR_DATE

,t1.FISCVARNT as FISCAL_YEAR_VARIANT 
,t1."/BIC/TUCFISQUA" as FISCAL_YEAR_QUARTER

,CASE
  WHEN t1."/BIC/TUDBILLDE" IS NULL OR t1."/BIC/TUDBILLDE" = '' OR t1."/BIC/TUDBILLDE" = '00000000'  THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDBILLDE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS BILL_DATE

,t1.CALWEEK as CALENDAR_YEAR_WEEK

,CASE
  WHEN calday IS NULL OR calday = '' OR calday  = '00000000'  THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(calday, 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS CALENDAR_DAY

,t1.FISCPER as FISCAL_YEAR_PERIOD
,t1.CALMONTH as CALENDAR_YEAR_MONTH
,t1.CALMONTH2 as CALENDAR_MONTH_2
,t1.FISCPER3 as POSTING_PERIOD
,t1.FISCYEAR as FISCAL_YEAR
,t1.CALQUART1 as QUARTER
,t1.CALQUARTER as CALENDAR_YEAR_QUARTER
,t1.CALYEAR as CALENDAR_YEAR
,NULL AS ELECT_COMMERCE_GRP

,CASE
  WHEN t1."/BIC/TUDBILLDE" IS NULL OR t1."/BIC/TUDBILLDE" = '' OR t1."/BIC/TUDBILLDE" = '00000000'  THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t1."/BIC/TUDBILLDE", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS BILL_DOC_DATE

,NULL AS LOADING_DATE
, t7."/BIC/TUCNAMEE" as CUST_NAME 
, t7."/BIC/TUCACCNTP" as ACCNT_TYPE
,nvl(cis_cust_xref.mcust_no, t3."/BIC/TUCHIEC03") as GROUPKEY
,NULL as SBU_HRCHY_L0
,pc.SBU_HRCHY_L1 as SBU_HRCHY_L1
,pc.SBU_HRCHY_L2 as SBU_HRCHY_L2
,pc.SBU_HRCHY_L3 as SBU_HRCHY_L3
,pc.SBU_HRCHY_L4 as SBU_HRCHY_L4
,pc.SBU_HRCHY_L1_TXT as SBU_HRCHY_L1_TXT
,pc.SBU_HRCHY_L2_TXT as SBU_HRCHY_L2_TXT
,pc.SBU_HRCHY_L3_TXT as SBU_HRCHY_L3_TXT
,pc.SBU_HRCHY_L4_TXT as SBU_HRCHY_L4_TXT
,NULL as TM1_HRCHY_L1
,NULL as TM1_HRCHY_L2
,NULL as TM1_HRCHY_L3
,NULL as TM1_HRCHY_L4
,matl.glbl_mfr   as GLBL_MFR
,matl.prod_family as  PROD_FAMILY
,matl.prod_class as PROD_CLASS
,matl.prod_subclass as  PROD_SUBCLASS
,t1."/BIC/TUCSALESG" AS LEGACY_SALES_ORG
,SYSDATE() as UPDATE_DATE_UTC 
from {{ source('us_cdp_bw_46','TUBLIO001') }} as t1
--from ANALYTICS.EDW_SAP_BW_US_46.TUBLIO001 as t1
left join {{ source('us_cdp_bw_46','TUCDOCTYX') }}  as t2  
--left join ANALYTICS.EDW_SAP_BW_US_46.TUCDOCTYX  as t2  
   on t1."/BIC/TUCDOCTYX" = t2."/BIC/TUCDOCTYX"
  and t2."/BIC/TUCDOCTP1" in ('1','2','5')  
left join {{ source('us_cdp_bw_46','TUCCUSTSS') }} as t3
--left join ANALYTICS.EDW_SAP_BW_US_46.TUCCUSTSS as t3
   on t1."/BIC/TUCSOLDTO" = t3."/BIC/TUCCUSTSS" 
   and t1."/BIC/TUCSALESG" = t3."/BIC/TUCSALESG"
   and t3."/BIC/TUCDIVISN" = '10'
   and t3.SOURSYSTEM = 'A3'
   and t3."/BIC/TUCDISTRN" = '00'
   and t3."/BIC/TUCACCNTN" in ('','01')   
left join {{ source('us_cdp_bw_46','TUCITEMCG') }}  as t4 
--left join ANALYTICS.EDW_SAP_BW_US_46.TUCITEMCG  as t4 
   on t1."/BIC/TUCITEMCG" = t4."/BIC/TUCITEMCG"
  and t4."/BIC/TUCITEMCA" in ('','1','3')   
left join {{ source('us_cdp_bw_46','TUCBILLTE') }}  as t5 
--left join ANALYTICS.EDW_SAP_BW_US_46.TUCBILLTE  as t5 
   on t1."/BIC/TUCBILLTE" = t5."/BIC/TUCBILLTE"
  and t5."/BIC/TUCBILLT1" in ('','2','3','5')    
left join {{ source('us_cdp_bw_46','TUCKTGRM') }}  as t6 
--left join ANALYTICS.EDW_SAP_BW_US_46.TUCKTGRM  as t6 
   on t1."/BIC/TUCKTGRM" = t6."/BIC/TUCKTGRM"
   and t6."/BIC/TUCKTGGR" = 'NSB'   
left join {{ source('us_cdp_bw_46','TUCCUSTOR') }}   as t7
--left join ANALYTICS.EDW_SAP_BW_US_46.TUCCUSTOR as t7
   on t1."/BIC/TUCSOLDTO" = t7."/BIC/TUCCUSTOR" 
  and t7.SOURSYSTEM = 'A3'
  and t7."/BIC/TUCACCNTP" <> 'ZIC'
left join cust
  on t1."/BIC/TUCSOLDTO" = cust.TUCCUSTSS  
left join {{ ref('profit_center_master') }}  pc
--left join US_DATAPRACTICE.CORE.PROFIT_CENTER_MASTER  pc
  on t1."/BIC/TUCPROFIR" = pc.PROFIT_CENTER  
left join matl
  on ltrim(t1."/BIC/TUCMATERL",'0') = ltrim(matl.material_id,'0')
  and t1.soursystem = matl.soursystem
  and t1."/BIC/TUCSALESG" = matl.sales_org  
  and matl.distr_channel = '00'   
left join cis_cust_xref
  ON ltrim(T1."/BIC/TUCSOLDTO",0) = cis_cust_xref.xref
  AND cis_cust_xref.xref_no = '1'
  
union all 
-- part 2 SAP 6.8

select 
md5(concat("/BIC/TNCBITEM", "/BIC/TNCBNUM", "/BIC/TNCBLGNUM", "/BIC/TNCBLGTYP", "/BIC/TNBILL_NM", BILL_ITEM, t68_1.SOURSYSTEM, '')) as BILLING_KEY
,md5("/BIC/TNPROFITC") as PROFIT_CENTER_MASTER_KEY
,md5(concat(t68_1.SOURSYSTEM, t68_1."/BIC/TNSALEORG", '00', '01', "/BIC/TNSOLDTO")) as CUSTOMER_MASTER_KEY
,md5(concat(t68_1.SOURSYSTEM,t68_1."/BIC/TNMATERIL", t68_1."/BIC/TNSALEORG", '01')) as MATERIAL_MASTER_KEY
,t68_3.TUCCUSTOR_46 as RESELLER_ID_46
,nvl(cis_cust_xref.mcust_no, t68_1."/BIC/TNSOLDTO") as RESELLER_ID_COMBINED
,t68_1."/BIC/TNSOLDTO" AS RESELLER_ID_68
,t68_1."/BIC/TNCBITEM" AS IP_CHARGEBACK_DOC_ITEM
,t68_1."/BIC/TNCBNUM" AS IP_CHARGEBACK_DOC_NBR
,t68_1."/BIC/TNCBLGNUM" AS IP_CHARGEBACK_LOG_DOC_NBR
,t68_1."/BIC/TNCBLGTYP" AS IP_CHARGEBACK_LOG_TYPE
,t68_1."/BIC/TNBILL_NM" AS BILL_DOC
,t68_1.BILL_ITEM AS BILL_ITEM
,t68_1.SOURSYSTEM AS SOURSYSTEM
,NULL AS BW_DELTA_PROCESS
,NULL AS PROMO_OPTIMIZATIN
,NULL AS CUST_PROJECT_NAME
,NULL AS CUST_REBATE_FLAG
,NULL AS SPECIAL_STOCK
,NULL AS TECH_DATA_AS_A_SERVICE
,t68_1."/BIC/TNMATERIL" AS MATERIAL_ID
,NULL AS REVERSAL_IND
,NULL AS LAST_CHANGED_ON
,NULL AS SALES_DISTRICT
,NULL AS BILL_TYPE
,NULL AS BILL_CTGRY
,NULL AS CUST_GRP
,NULL AS PAYER
,NULL AS PROMOTION
,t68_1."/BIC/TND_NUMB" AS SALES_DOC
,t68_1.S_ORD_ITEM AS SALES_DOC_ITEM 
,NULL AS VOLUME_REBATE_GRP
,NULL AS BATCH_NBR
,NULL AS EUROPEAN_ARTICLE_NBR
,NULL AS SERVICES_RENDERED_DATE
,NULL AS SALES_DEAL
,NULL AS CONVERSION_DATE
,NULL AS CUST_PRICING_COLUMN
,NULL AS PROFILE_COLUMN
,NULL AS CUST_GRP_2
,NULL AS FREIGHT_COLUMN
,NULL AS SPECIAL_HANDLING_MD
,NULL AS ORDER_FULFILLMENT
,t68_1."/BIC/TNSTOR_LO" AS STORAGE_LOCATION
,NULL AS MATERIAL_ENTERED
,NULL AS BUSINESS_MANAGER
,NULL AS DIVISION_MANAGER
,NULL AS DIRECTOR 
,NULL AS REPAIR_TIME_DAYS
,NULL AS INVESTIGATION_RESULT
,t68_1."/BIC/TNBILL_TO" AS BILL_TO_PARTY
,t68_1."/BIC/TNSHIP_TO" AS SHIP_TO_PARTY
,NULL AS ITEM_TYPE
,t68_1."/BIC/TNPROFITC" AS PROFIT_CENTER
,NULL AS PROD_HRCHY
,NULL AS COMMISSION_GRP
,NULL AS PRICING_EXCHANGE_RATE_DATE
,NULL AS SALES_DOC_ITEM_CAT
,NULL AS SALES_EMPLOYEE
,NULL AS STATS_DATE
,NULL AS UPDATE_DATE_STATS
,NULL AS DOC_NBR_OF_REF_DOC
,NULL AS SAP_INTERNAL_DELIVERY_NBR
,NULL AS ITEM_NBR_OF_REF_ITEM
,NULL AS SALES_OFFICE
,NULL AS SHIPPING_POINT
,NULL AS PLANT
,NULL AS EXCHANGE_RATE_TYPE
,NULL AS SALES_DOC_CAT
,NULL AS CONTROLLING_AREA
,NULL AS COST_CENTER
,NULL AS MATERIAL_GRP
,NULL AS DIVISION_ORDER_HEADER
,NULL AS SALES_GRP
,NULL AS APPLICATION_COMPONENT
,NULL AS BW_TRANSACTION_KEY
,NULL AS SUPER_SALES_AREA
,NULL AS SALES_AREA
,NULL AS SALES_EXECUTIVE
,NULL AS CUST_HRCHY_LVL_4 
,NULL AS CUST_HRCHY_LVL_5
,NULL AS ACCNT_ASSIGN_GRP_MATERIAL
,NULL AS DND_REASON
,t68_3.TNCCUSTYP as CUST_ACCNT_ASGMT_GRP
,NULL AS SHIPPING_CONDS
,NULL AS REF_DOC_NBR
,NULL AS RULE_IN_BILL_PLAN
,makt.maktx AS SALES_ORDER_ITEM_SHORT
,NULL AS MANUAL_PRICE_CHANGE
,NULL AS PRECEDING_DOC_CAT
,NULL AS ERMA_NBR
,NULL AS END_USER_DATE
,NULL AS END_USER_INVOICE_NBR
,NULL AS ACCESSORIES
,NULL AS WARRANTY_IND
,NULL AS NAME_OF_ORDERER
,NULL AS CUST_PART_NBR
,NULL AS END_CUST_NBR
,NULL AS FREE_PROJECT_NBR
,NULL AS DRM_AGREEMENT_NO_TEX
,NULL AS PA_SF_REASON_CODE
,NULL AS CUST_VENDOR_INTERNAL_REF
,NULL AS SHIP_TO_PARTY_ORDER_NBR
,NULL AS PAYMENT_TERMS
,NULL AS NEGATIVE_FEM_FLAG
,NULL AS PP_CODE
,NULL AS SALES_PROJECT_OWNER
,NULL AS CREATED_BY 
,NULL AS ARCHIVE_FLAG
,NULL AS TEXCHANGE_RATE_FI_POSTINGS
,NULL AS REBATE_BASIS_1
,NULL AS GROSS_WEIGHT
,t68_1.BILL_QTY AS BILLED_QTY_SALES_UNITS
,NULL AS BILL_QTY_BASE_UNITS
,NULL AS BILLED_QTY_ORIGINAL
,NULL AS EXCHANGE_RATE_PRICING_STATS
,NULL AS EXACT_EXCHANGE_RATE_FI_POSTING
,NULL AS REQUIRED_QTY_MAT_MNGMT
,NULL AS TAX_AMOUNT_DC
,NULL AS NET_WEIGHT
,NULL AS AMOUNT_CASH_DISCOUNT_DC
,NULL AS SCALE_QTY_BASE_UNIT
,NULL AS DIVISOR_SALES_QTY_TO_SKU
,NULL AS FACTOR_SALES_QTY_TO_SKU
,NULL AS VOLUME_DELIVERED
,T68_1."/BIC/TNCOSTDC" AS COST_DC 
,NULL AS NBR_BILL_ITEMS
,NULL AS COND_SUBTOTAL_1
,NULL AS SYSTEM_SELL_PRICE_DC
,NULL AS PROPOSED_FREIGHT_DOC
,NULL AS COND_SUBTOTAL_4
,NULL AS FRONT_END_PROFIT_DOC
,NULL AS COND_SUBTOTAL_6
,NULL AS NET_VALUE_BILL_ITEM_
,NULL AS XCHANGE_RATE_STATS
,NULL AS GROSS_WEIGHT_SD_DC
,T68_1.DOC_CURRCY AS DOC_CURR 
,NULL AS WEIGHT_UNIT
,NULL AS SALES_UNIT
,NULL AS BASE_UNIT
,NULL AS VOLUME_UNIT
,T68_1.STAT_CURR AS STATS_CUR
,T68_1.LOC_CURRCY AS LOC_CUR
,NULL AS REQ_DELIVERY_DATE
,t68_1."/BIC/TNSODOCTP" AS SALES_DOC_TYPE 
,NULL AS SO_ITEM_CREATED_BY
,NULL AS METHOD_ORDER_TAKING
,NULL AS LP_LIST_PRICE
,NULL AS RATE_UNIT_CUR_OR_PERC
,NULL AS COND_RATE_PURCH_PRICE
,NULL AS CUR_KEY_PURCH_COST
,NULL AS COND_RATE_ADJ_COST
,NULL AS CUR_KEY_ADJ_COST
,t68_1."/BIC/TNZZA21" AS SELL_PRICE_LC
,t68_1."/BIC/TNZZA21" AS SYSTEM_SELL_PRICE_LC
,NULL AS PROPOSED_FREIGHT_LC
,T68_1."/BIC/TNFRACDC" AS ACTUAL_FREIGHT_LC
,t68_1."/BIC/TNZZV07" AS FRONT_END_PROFIT_LC
,t68_1."/BIC/TNZZA22" AS NET_SALES_PROFIT_LC
,t68_1."/BIC/TNZZA17" AS NET_VALUE_LC
,t68_1."/BIC/TNXCOSTLC" AS COST_LC
,t68_1."/BIC/TNXRSLUSD" AS SELL_PRICE_EUR
,t68_1."/BIC/TNXRSLUSD" AS SYSTEM_SELL_PRICE_EUR
,NULL AS PROPOSED_FREIGHT_EUR
,NULL AS ACTUAL_FREIGHT_EUR
,t68_1."/BIC/TNSAM07" AS FRONT_END_PROFIT_EUR
,t68_1."/BIC/TNGPUSD" AS NET_SALES_PROFIT_EUR
,t68_1."/BIC/TNZZA17" AS NET_VALUE_EUR
,t68_1."/BIC/TNXCOSTUS" AS COST_EUR 
,NULL AS SHIPPING_TYPE
,NULL AS DIVISION
,'US01' as COMPANY_CODE
,'US01' as SALES_ORG
,'01' AS DISTR_CHANNEL
,NULL AS USAGE_IND_MATERIAL
,NULL AS CREDIT_CONTROL_AREA
,NULL AS CREDIT_MGMT_REPS_GRP
,NULL AS PRICING_COND
,NULL AS MATERIAL_PRICING_GRP
,NULL AS BILL_DOC_IS_CANCELLED
,NULL AS CANCELLED_BILL_DOC_NBR
,NULL AS SND_FLAG
,NULL AS PRICING_COND_COUNTER
,NULL AS CUST_PO_NBR
,t68_1."/BIC/TNSOLDTO" AS RESELLER_ID
,NULL AS MATERIAL_PLANT
,NULL AS MATERIAL_SALES
,NULL AS MATERIAL_STORAGE_LOC
,NULL AS RESELLER_ID_CC
,NULL AS RESELLER_ID_SS
,t68_1."/BIC/TNEND_CUS" AS END_USER_DETAIL_INFO
,t68_1."/BIC/TNSHIP_TO" AS SHIP_TO_DETAIL_INFO
,NULL AS USAGE_IND_HEADER 
,NULL AS POD_RELEVANT
,NULL AS REGIONAL_SALES_ITEM
,NULL AS SALES_ITEM_FLAG
,NULL AS CREATION_DATE
,NULL AS LOADING_DATE_INTO_BW
,NULL AS BUMPED_PRICE_DOC
,NULL AS BUMPED_PRICE_LC
,NULL AS SND_CUST_ALLOW
,NULL AS SND_CUST_ALLOW_LC 
,NULL AS KIT_SND_CUST_ALLOW
,NULL AS KIT_SND_CUST_ALLOW_LC
,NULL AS SYS_NSP_DOC_PRICE
,NULL AS SYS_NSP_CUST_PRICE_LC
,NULL AS NSP_DOC_PRICE
,T68_1."/BIC/TNZZA17" AS NSP_LC
,t68_1."/BIC/TNZZA17" AS NSP_EUR
,NULL AS SND_VENDOR_ALLOW_DC
,NULL AS SND_VENDOR_ALLOW_LC
,NULL AS PC_PRICE
,NULL AS PC_PRICE_LC
,NULL AS MAN_PRICING_IND
,NULL AS BUMP_VALUE_DOC
,NULL AS BUMP_VALUE_LC
,NULL AS GOV_FEE_DOC
,NULL AS GOV_FEE_LC
,NULL AS VELOCITY_DOC
,NULL AS VELOCITY_LC
,NULL AS INTOUCH_DISCOUNT_DOC
,NULL AS INTOUCH_DISCOUNT_LC
,NULL AS PC_PRICE_VENDOR_CUR
,NULL AS VENDORS_CUR
,NULL AS END_CUST_PRICE_REF_LC
,NULL AS AC_PRICE
,NULL AS AC_PRICE_LC
,NULL AS TOTAL_CA_ON_AC_KIT_COMP
,NULL AS TOTAL_CA_ON_AC_KIT_COMP_LC
,NULL AS TOTAL_CA_ON_AC_KIT_HEADER
,NULL AS TOTAL_CA_ON_AC_KIT_HEADER_LCL
,NULL AS SALES_ADJ_PROFIT
,NULL AS SALES_ADJ_PROFIT_LC
,NULL AS WEEE_GOV_FEE
,NULL AS WEEE_GOV_FEE_LC
,NULL AS FUNCTIONAL_DISCOUNT
,NULL AS FUNCTIONAL_DISCOUNT_LC 

,CASE
  WHEN t68_1."/BIC/TNSOCRDAT" IS NULL OR t68_1."/BIC/TNSOCRDAT" = '' OR t68_1."/BIC/TNSOCRDAT" = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t68_1."/BIC/TNSOCRDAT", 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS SALES_ORDER_DATE

,NULL AS WARRANTY 
,NULL AS EDI_ENDCUST_INVOICE
,NULL AS UTC_TIME_STAMP
,NULL AS SOLD_TO_PARTY_DETAIL
,NULL AS MIN_ORDER_SURCHARGE_DC
,NULL AS MIN_ORDER_SURCHARGE_LC
,NULL AS ACTUAL_VEITY_LC
,NULL AS ADD_FREIGHT_TOLLS_DC
,NULL AS ADD_FREIGHT_TOLLS_LC
,NULL AS ARCHIVING_DATE
,NULL AS PC_PRICE_VENDOR_CUR_SO
,NULL AS PRICING_DATE_SO 
,NULL AS BEM_2_DOC
,NULL AS BEM_2_LC
,NULL AS FREIGHT_COSTS_LC
,NULL AS FREIGHT_COSTS_DOC
,NULL AS NET_FREIGHT_DOC
,NULL AS NET_FREIGHT_LC
,NULL AS LOGISTIC_COSTS_DOC 
,NULL AS LOGISTIC_COSTS_LC
,NULL AS FINANCIAL_COSTS_DOC
,NULL AS FINANCIAL_COSTS_LC
,NULL AS MIN_POM_DOC
,NULL AS MIN_POM_LC
,NULL AS POCKET_MARGIN_DOC
,NULL AS POCKET_MARGIN_LC
,NULL AS DIESEL_SURCHARGE_DOC
,NULL AS DIESEL_SURCHARGE_LC
,NULL AS ADD_POM_FACTOR_DOC
,NULL AS ADD_POM_FACTOR_LC
,NULL AS COND_ZRET_ASM_BUMP_DOC
,NULL AS COND_ZRET_ASM_BUMP_LC
,NULL AS FREIGHT_BUMP_ZZ78_DOC
,NULL AS FREIGHT_BUMP_ZZ78_LC
,NULL AS COND_DATE
,NULL AS COPY_RIGHT_TAX_ZZG9
,NULL AS COPY_RIGHT_TAX_ZZG9_LC
,NULL AS COND_DATE_SO
,NULL AS COND_ZZG6_GOV_FEE_DOC
,NULL AS COND_ZZG6_GOV_FEE_LC
,NULL AS COND_ZZ94_RETAIL_DISCOUNT_DOC
,NULL AS COND_ZZ94_RETAIL_DISCOUNT_LC
,NULL AS COND_ZEDI_EDI1_PRICE_DIFF
,NULL AS COND_ZEDI_EDI1_PRICE_DIFF_LC
,NULL AS COND_ZZ74_ENV_FEE_HEADER
,NULL AS COND_ZZ74_ENV_FEE_HEADER_LC
,NULL AS VAT_REGISTRATION_NBR
,NULL AS TD_VAT_REGISTRATION_NBR
,NULL AS ALT_TAX_CLASS
,NULL AS TAX_CLASS
,NULL AS PROPOSED_MIN_QTY_SURCHARGE
,NULL AS ACTUAL_MIN_QTY_SURCHARGE
,NULL AS PROPOSED_MIN_QTY_SURCHARGE_LC
,NULL AS ACTUAL_MIN_QTY_SURCHARGE_LC
,NULL AS SPEC_STOCKPARTN
,NULL AS SPEC_STOCKPART_ID
,NULL AS DELIVERY_PRIO
,NULL AS MATERIAL_TIME_DEPEND
,NULL AS MATERIAL_PLANT_TIME_DEPEND
,NULL AS MATERIAL_SALES_TIME_DEPENDL
,NULL AS CUST_SALES_TIME_DEPEND 
,NULL AS INITIAL_PLANT
,NULL AS EXPORT_FLAG
,NULL AS ORDER_BUCKET_CODE
,NULL AS BUSINESS_ORDER_TYPE
,NULL AS BUSINESS_ORDER_LVL
,NULL AS BASIS_FREIGHT_LC
,NULL AS WASHINGTON_STATE_FEE_LC
,NULL AS FRONT_END_MARGIN_AC_LC
,NULL AS NET_SALES_MARGIN_AC_LC
,NULL AS SALES_ADJ_MARGIN_AC_LC
,NULL AS POCKET_MARGIN_AC_LC
,NULL AS SELF_FOUNDED_PROMO_LC
,NULL AS BASIS_FREIGHT_DOC
,NULL AS WASHINGTON_STATE_FEE_DOC
,NULL AS FRONT_END_MARGIN_AC_DOC
,NULL AS NET_SALES_MARGIN_AC_DOC
,NULL AS SALES_ADJ_MARGIN_AC_DOC
,NULL AS POCKET_MARGIN_AC_DOC
,NULL AS SELF_FOUNDED_PROMO_DOC
,NULL AS NBR_PAYMENT_CARD_PLAN
,NULL AS OUT_ZONE_FLAG
,NULL AS GPMM_MANUAL_PRICE
,NULL AS EXTENDED_VENDOR_PURCH_COST_VC
,NULL AS EXTENDED_VENDOR_PURCH_COST_LC
,NULL AS PC_PRICE_LC_2
,NULL AS EXTENDED_VENDOR_PURCH_COST_DC
,NULL AS PC_PRICE_DC
,NULL AS VENDOR_REBATES_LC
,NULL AS VENDOR_REBATES
,NULL AS LINE_LVL_SHIP_COND
,NULL AS BILL_TO_DETAIL_INFO
,NULL AS CUST_DETAILS_INFO
,NULL AS NBR_DOC_COND
,NULL AS SND_RED_AC_DOC
,NULL AS SND_RED_AC_ZZKZWI4_LC
,NULL AS HRZN_FRA2_FLAG
,NULL AS FREIGHT_ADDER_VALUE_LC
,NULL AS IBU_FLAG
,NULL AS IBU_ADDER_VALUE_LC
,NULL AS ROYALTY_ADDER_FLAG
,NULL AS ROYALTY_ADDER_VALUE
,NULL AS CUSTOM_FLAG
,NULL AS CUSTOME_VALUE_LC 
,NULL AS ROYALTY_CUR
,NULL AS ORIGINAL_BILL_DATE
,NULL AS FIXED_VENDOR_SOURCE_LIST
,t68_1.calmonth2 AS CALENDAR_MONTH
,t68_1."/BIC/AACALQTR" AS FISCAL_QUARTER
,NULL AS HIGH_LVL_ITEM_SO
,t68_1.calquarter AS CALENDAR_QUARTER
,NULL AS HIGHER_LVL_DOC_ITEM_NBR
,NULL AS BUMP_VOLUME_REB_VAL
,NULL AS BUMP_EXCL_VOL_REB
,NULL AS CUST_REBATE_VALUE 
,NULL AS CUST_REBATE_EXCL
,NULL AS CUST_REBATE_MDF
,NULL AS CUST_REBATE_EXCL_MDF
,NULL AS TIME_CREATED
,NULL AS BUMP_VOLUME_REB_PERC
,NULL AS BUMP_EXCL_VOL_REB_PERC
,NULL AS TOTAL_REBATE_BUMP 
,NULL AS TOTAL_CUST_REBATE
,NULL AS BUNDLE_ID
,NULL AS BUMPED_BEST_PRICE_DOC
,NULL AS BUMPED_BEST_PRICE_LC
,NULL AS VENDOR_PROGRAM
,NULL AS DAYS_TO_INVOICE
,NULL AS PRICING_EXCEPTION_FLAG
,NULL AS POS_REPORTING_DATE
,NULL AS DAYS_TO_INVOICE_2
,NULL AS SERVICES_SOURCING
,NULL AS SERVICES_TECHNOLOGY
,NULL AS DND_REASON_NON_EMEA
,NULL AS FOREX_CORRECTED_FEM
,NULL AS FOREX_CORRECTED_FEP_LC
,NULL AS FOREX_CORRECTED_NSM
,NULL AS FOREX_CORRECTED_NSP_LC
,NULL AS FOREX_CORRECTED_SAM
,NULL AS FOREX_CORRECTED_SAP_LC
,NULL AS FOREX_CORRECTED_POM
,NULL AS FOREX_CORRECTED_POP_LC
,NULL AS CUSTS_ACCNT_NBR_CL_REF
,NULL AS UPDATE_FLAG
,NULL AS FLOORPLAN_SPONSORED_DOC
,NULL AS FLOORPLAN_SPONSORED_LC
,NULL AS MANUAL_GOV_FEE_DOC
,NULL AS MANUAL_GOV_FEE_LC 
,NULL AS AC_PLUS_INS_TAX_VALUE
,NULL AS AC_PLUS_RESELLER_COMMISSION
,NULL AS AC_PLUS_VENDOR_COMMISSION
,NULL AS AC_PLUS_TD_VENDOR_REBATE
,NULL AS AC_PLUS_TD_RESELLER_REBATE
,NULL AS AC_PLUS_VENDOR_REBATE_REF
,NULL AS INS_SUPPLIER
,NULL AS AC_PLUS_INS_TAX_VALUE_LC
,NULL AS AC_PLUS_RESELLER_COMMISSION_LC
,NULL AS AC_PLUS_VENDOR_COMMISSION_LC
,NULL AS DELIVERY_GRP
,NULL AS AC_PLUS_INS_PREMIUM_TAX_PERC
,NULL AS END_USER_INFO
,NULL AS TDM_MDF_ON_INVOICE
,NULL AS TDM_MDF_ON_INVOICE_LC
,NULL AS TDM_HW_SUBSIDY 
,NULL AS TDM_HW_SUBSIDY_LC
,NULL AS ORIGINAL_SELL_PRICE_
,NULL AS ORIGINAL_COST_SUBSCR_LC
,NULL AS SUBTOTAL_GOV_FEES
,NULL AS SUBTOTAL_GOV_FEES_LC
,NULL AS SND_BASE_DP_RATE1
,NULL AS SND_BASE_DP_RATE_LC 
,NULL AS RED_FEM_PERC_YAN0
,NULL AS RED_FEM_USD_YAN0
,NULL AS MINMARG_PERC_YAPB 
,NULL AS MINMARG_USD_YAPB
,NULL AS RED_FEM_PERC_YAN0_LC
,NULL AS RED_FEM_USD_YAN0_LC
,NULL AS MINMARG_PERC_YAPB_LC
,NULL AS MINMARG_USD_YAPB_LC
,NULL AS WEB_DISCOUNT_VALUE_LC
,NULL AS WEB_DISCOUNT_VALUE
,NULL AS TAX_AMOUNT_LC
,NULL AS VOUCHER_NBR 
,NULL AS VOUCHER_VENDOR_ID
,NULL AS VOUCHER_VALUE_LC
,NULL AS VOUCHER_VALUE_DOC
,NULL AS LINE_ORDER_TYPE
,NULL AS ORDER_CONSOLIDATION
,NULL AS CHEM_FEE_STOCK_HOLDER
,NULL AS SPECIAL_STOCK_IND
,NULL AS BTO_CUM_VALUE_DOC
,NULL AS BAD_BOX_ALLOW_DC
,NULL AS BTO_ID
,NULL AS INVENTORY_KEY_SALES
,NULL AS MATERIAL_TYPE
,NULL AS BAD_BOX_ALLOW_LC 
,NULL AS BTO_CUM_VALUE_LC 
,NULL AS SBU_HRCHY_L1_OLD 

,CASE
  WHEN t68_1.calday IS NULL OR t68_1.calday = '' OR t68_1.calday = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t68_1.calday, 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS CALENDAR_DATE

,NULL AS FISCAL_YEAR_VARIANT 
,t68_1."/BIC/NFSCQTR2" AS FISCAL_YEAR_QUARTER

,CASE
  WHEN t68_1.bill_date IS NULL OR t68_1.bill_date = '' OR t68_1.bill_date = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t68_1.bill_date, 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS BILL_DATE

,t68_1.calweek AS CALENDAR_YEAR_WEEK

,CASE
  WHEN t68_1.calday IS NULL OR t68_1.calday = '' OR t68_1.calday = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t68_1.calday, 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS CALENDAR_DAY

,t68_1.fiscper AS FISCAL_YEAR_PERIOD
,t68_1.CALMONTH AS CALENDAR_YEAR_MONTH
,t68_1.calmonth2 AS CALENDAR_MONTH_2
,t68_1.fiscper3 AS POSTING_PERIOD
,t68_1.fiscyear AS FISCAL_YEAR 
,t68_1."/BIC/AACALQTR" AS QUARTER
,t68_1.CALQUARTER AS CALENDAR_YEAR_QUARTER
,t68_1.calyear AS CALENDAR_YEAR
,NULL AS ELECT_COMMERCE_GRP

,CASE
  WHEN t68_1.bill_date IS NULL OR t68_1.bill_date = '' OR t68_1.bill_date = '00000000' THEN NULL
  ELSE TO_DATE(TO_CHAR(TO_DATE(t68_1.bill_date, 'YYYYMMDD'), 'YYYY-MM-DD'))
END AS BILL_DOC_DATE

,NULL AS LOADING_DATE  
,t68_3.TNCBPCUST_TEXT as CUST_NAME
,NULL AS ACCNT_TYPE
,nvl(cis_cust_xref.mcust_no, nvl(t68_3.TUCKONZS, t68_3.TNECUSNU)) as GROUPKEY
,NULL as SBU_HRCHY_L0
,NULL as SBU_HRCHY_L1
,NULL as SBU_HRCHY_L2
,NULL as SBU_HRCHY_L3
,NULL as SBU_HRCHY_L4
,NULL as SBU_HRCHY_L1_TXT
,NULL as SBU_HRCHY_L2_TXT
,NULL as SBU_HRCHY_L3_TXT
,NULL as SBU_HRCHY_L4_TXT
,NULL as TM1_HRCHY_L1
,NULL as TM1_HRCHY_L2
,NULL as TM1_HRCHY_L3
,NULL as TM1_HRCHY_L4
,matl.GLBL_MFR as GLBL_MFR
,matl1."/BIC/TNPMMGDS1" as PROD_FAMILY
,matl1."/BIC/TNPMMGDS2" as PROD_CLASS
,matl1."/BIC/TNPMMGDS3" as PROD_SUBCLASS
,t68_1."/BIC/TNSALEORG" AS LEGACY_SALES_ORG
,SYSDATE() as UPDATE_DATE_UTC 
from {{ source('us_cdp_bw_68','TNBLIO02') }}  as t68_1
left join {{ source('us_cdp','CUSTOMERMASTER_BASE_68_MAPPED') }}   as t68_3 
--from ANALYTICS.EDW_SAP_BW_US_68.TNBLIO02  as t68_1
--left join US_DATAPRACTICE.CDP.CUSTOMERMASTER_BASE_68_MAPPED  as t68_3 
  on t68_1."/BIC/TNSOLDTO" = t68_3.TNCBPCUST
  and t68_1."/BIC/TNSALEORG" = t68_3.TNSALEORG  

left join cust
  on t68_1."/BIC/TNSOLDTO" = cust.tncbpcust

left join matl
  on t68_1."/BIC/TNMATERIL" = matl.material_id
  and t68_1.soursystem = matl.soursystem
  and t68_1."/BIC/TNSALEORG" = matl.sales_org
  
left join {{ source('us_cdp_ecc_68','MAKT') }} makt
--left join ANALYTICS.EDW_SAP_ECC_US_68.MAKT  makt
  on t68_1."/BIC/TNMATERIL" = makt.matnr
  and makt.spras = 'E' 
left join cis_cust_xref
  on ltrim(t68_1."/BIC/TNSOLDTO",0) = cis_cust_xref.xref
  and cis_cust_xref.xref_no = '68'
left join ANALYTICS.EDW_SAP_BW_US_68.TNMATERIL matl1
  on t68_1."/BIC/TNMATERIL" = matl1."/BIC/TNMATERIL"
  and matl1.soursystem = 'A2'

union all 
 --part 3
select 
 md5(concat('CIS_US', lpad(to_char(inv.ORDER_NO), 38, '0'), lpad(to_char(inv.ORDER_LINE_NO),38,'0'), to_char(inv.ORDER_TYPE))) as billing_key
,md5(concat('CIS US', to_char(matl.vpl_no))) as profit_center_master_key
,md5(concat('CIS_US', to_char(inv.cust_no))) as customer_key
,md5(concat('CIS_US', to_char(matl.sku_no))) as material_key
, NULL as RESELLER_ID_46
, to_char(inv.cust_no) as RESELLER_ID_COMBINED
, NULL as RESELLER_ID_68
, NULL as IP_CHARGEBACK_DOC_ITEM
, NULL as IP_CHARGEBACK_DOC_NBR
, NULL as IP_CHARGEBACK_LOG_DOC_NBR
, NULL as IP_CHARGEBACK_LOG_TYPE
, to_char(inv.order_no) as BILL_DOC
, to_char(inv.order_line_no) as BILL_ITEM
, 'CIS_US' as SOURSYSTEM
, NULL as BW_DELTA_PROCESS
, NULL as PROMO_OPTIMIZATIN
, NULL as CUST_PROJECT_NAME
, NULL as CUST_REBATE_FLAG
, NULL as SPECIAL_STOCK
, NULL as TECH_DATA_AS_A_SERVICE
, to_char(matl.sku_no) as MATERIAL_ID
, NULL as REVERSAL_IND
, NULL  as LAST_CHANGED_ON 
, NULL as SALES_DISTRICT
, to_char(inv.order_type) as BILL_TYPE
, NULL as BILL_CTGRY
, NULL as CUST_GRP
, NULL as PAYER
, NULL as PROMOTION
, to_char(inv.order_no) as SALES_DOC
, to_char(inv.order_line_no) as SALES_DOC_ITEM
, NULL as VOLUME_REBATE_GRP
, NULL as BATCH_NBR
, NULL as EUROPEAN_ARTICLE_NBR
, NULL  as SERVICES_RENDERED_DATE
, NULL as SALES_DEAL
, NULL  as CONVERSION_DATE
, NULL as CUST_PRICING_COLUMN
, NULL as PROFILE_COLUMN
, NULL as CUST_GRP_2
, NULL as FREIGHT_COLUMN
, NULL as SPECIAL_HANDLING_MD
, NULL as ORDER_FULFILLMENT
, NULL as STORAGE_LOCATION
, NULL as MATERIAL_ENTERED
, NULL as BUSINESS_MANAGER
, NULL as DIVISION_MANAGER
, NULL as DIRECTOR
, NULL as REPAIR_TIME_DAYS
, NULL as INVESTIGATION_RESULT
, NULL as BILL_TO_PARTY
, NULL as SHIP_TO_PARTY
, NULL as ITEM_TYPE
, to_char(pc.LEVEL_4_NAME) as PROFIT_CENTER
, NULL as PROD_HRCHY
, NULL as COMMISSION_GRP
, NULL  as PRICING_EXCHANGE_RATE_DATE
, NULL as SALES_DOC_ITEM_CAT
, NULL as SALES_EMPLOYEE
, NULL  as STATS_DATE
, NULL  as UPDATE_DATE_STATS
, NULL as DOC_NBR_OF_REF_DOC
, NULL as SAP_INTERNAL_DELIVERY_NBR
, NULL as ITEM_NBR_OF_REF_ITEM
, NULL as SALES_OFFICE
, NULL as SHIPPING_POINT
, to_char(inv.from_loc_no) as PLANT
, NULL as EXCHANGE_RATE_TYPE
, NULL as SALES_DOC_CAT
, NULL as CONTROLLING_AREA
, NULL as COST_CENTER
, NULL as MATERIAL_GRP
, NULL as DIVISION_ORDER_HEADER
, NULL as SALES_GRP
, NULL as APPLICATION_COMPONENT
, NULL as BW_TRANSACTION_KEY
, to_char(cust.division) as SUPER_SALES_AREA
, to_char(cust.cust_type) as SALES_AREA
, to_char(cust.sales_terr) as SALES_EXECUTIVE
, NULL as CUST_HRCHY_LVL_4
, NULL as CUST_HRCHY_LVL_5
, NULL as ACCNT_ASSIGN_GRP_MATERIAL
, NULL as DND_REASON
, CASE 
   WHEN cust.cust_acct_type IN(null, '') THEN 'UNKNOWN'
   ELSE UPPER(cust.cust_acct_type)
   END as CUST_ACCNT_ASGMT_GRP

, NULL as SHIPPING_CONDS
, NULL as REF_DOC_NBR
, NULL as RULE_IN_BILL_PLAN
, to_char(matl.short_desc) as SALES_ORDER_ITEM_SHORT
, NULL as MANUAL_PRICE_CHANGE
, NULL as PRECEDING_DOC_CAT
, NULL as ERMA_NBR
, NULL  as END_USER_DATE
, NULL as END_USER_INVOICE_NBR
, NULL as ACCESSORIES
, NULL as WARRANTY_IND
, NULL as NAME_OF_ORDERER
, NULL as CUST_PART_NBR
, NULL as END_CUST_NBR
, NULL as FREE_PROJECT_NBR
, NULL as DRM_AGREEMENT_NO_TEX
, NULL as PA_SF_REASON_CODE
, NULL as CUST_VENDOR_INTERNAL_REF
, NULL as SHIP_TO_PARTY_ORDER_NBR
, to_char(inv.terms) as PAYMENT_TERMS
, NULL as NEGATIVE_FEM_FLAG
, NULL as PP_CODE
, NULL as SALES_PROJECT_OWNER
, NULL as CREATED_BY
, NULL as ARCHIVE_FLAG
, NULL as EXCHANGE_RATE_FI_POSTINGS
, NULL as REBATE_BASIS_1
, NULL as GROSS_WEIGHT
, to_char(inv.ship_qty) as BILLED_QTY_SALES_UNITS
, NULL as BILL_QTY_BASE_UNITS
, NULL as BILLED_QTY_ORIGINAL
, NULL as EXCHANGE_RATE_PRICING_STATS
, NULL as EXACT_EXCHANGE_RATE_FI_POSTING
, NULL as REQUIRED_QTY_MAT_MNGMT
, NULL as TAX_AMOUNT_DC
, NULL as NET_WEIGHT
, NULL as AMOUNT_CASH_DISCOUNT_DC
, NULL as SCALE_QTY_BASE_UNIT
, NULL as DIVISOR_SALES_QTY_TO_SKU
, NULL as FACTOR_SALES_QTY_TO_SKU
, NULL as VOLUME_DELIVERED
, NULL as COST_DC
, NULL as NBR_BILL_ITEMS
, NULL as COND_SUBTOTAL_1
, NULL as SYSTEM_SELL_PRICE_DC
, NULL as PROPOSED_FREIGHT_DOC
, NULL as COND_SUBTOTAL_4
, NULL as FRONT_END_PROFIT_DOC
, NULL as COND_SUBTOTAL_6
, NULL as NET_VALUE_BILL_ITEM_
, NULL as EXCHANGE_RATE_STATS
, NULL as GROSS_WEIGHT_SD_DC
, NULL as DOC_CURR
, NULL as WEIGHT_UNIT
, NULL as SALES_UNIT
, NULL as BASE_UNIT
, NULL as VOLUME_UNIT
, NULL as STATS_CUR
, 'USD' as LOC_CUR
, NULL  as REQ_DELIVERY_DATE
, to_char(inv.order_type)  as SALES_DOC_TYPE
, NULL as SO_ITEM_CREATED_BY
, to_char(inv.from_ref_type) as METHOD_ORDER_TAKING
, NULL as LP_LIST_PRICE
, NULL as RATE_UNIT_CUR_OR_PERC
, NULL as COND_RATE_PURCH_PRICE
, NULL as CUR_KEY_PURCH_COST
, NULL as COND_RATE_ADJ_COST
, NULL as CUR_KEY_ADJ_COST
, to_char(inv.net_u_price) as SELL_PRICE_LC
, to_char(inv.net_u_price) as SYSTEM_SELL_PRICE_LC
, NULL as PROPOSED_FREIGHT_LC
, NULL as ACTUAL_FREIGHT_LC
, to_char(inv.net_u_price-inv.u_cost) as FRONT_END_PROFIT_LC
, NULL as NET_SALES_PROFIT_LC
, NULL as NET_VALUE_LC
, to_char(inv.u_cost) as COST_LC
, to_char(inv.fx_net_u_price) as SELL_PRICE_EUR
, to_char(inv.fx_net_u_price) as SYSTEM_SELL_PRICE_EUR
, NULL as PROPOSED_FREIGHT_EUR
, NULL as ACTUAL_FREIGHT_EUR
, to_char(inv.fx_net_u_price) - to_char(inv.fx_u_cost) as FRONT_END_PROFIT_EUR
, NULL as NET_SALES_PROFIT_EUR
, NULL as NET_VALUE_EUR
, to_char(inv.u_cost) as COST_EUR
, NULL as SHIPPING_TYPE
, NULL as DIVISION
, 'US01' as COMPANY_CODE
, 'US01' as SALES_ORG
, NULL as DISTR_CHANNEL
, NULL as USAGE_IND_MATERIAL
, NULL as CREDIT_CONTROL_AREA
, NULL as CREDIT_MGMT_REPS_GRP
, NULL as PRICING_COND
, NULL as MATERIAL_PRICING_GRP
, NULL as BILL_DOC_IS_CANCELLED
, NULL as CANCELLED_BILL_DOC_NBR
, NULL as SND_FLAG
, NULL as PRICING_COND_COUNTER
, NULL as CUST_PO_NBR
, to_char(inv.CUST_NO) as RESELLER_ID
, NULL as MATERIAL_PLANT
, NULL as MATERIAL_SALES
, NULL as MATERIAL_STORAGE_LOC
, NULL as RESELLER_ID_CC
, NULL as RESELLER_ID_SS
, to_char(eu.EU_LOC_ADDRESS1) as END_USER_DETAIL_INFO
, to_char(inv.SHIP_TO_ADDR) as SHIP_TO_DETAIL_INFO
, NULL as USAGE_IND_HEADER
, NULL as POD_RELEVANT
, NULL as REGIONAL_SALES_ITEM
, NULL as SALES_ITEM_FLAG
, inv.date_flag  as CREATION_DATE
, NULL as LOADING_DATE_INTO_BW
, NULL as BUMPED_PRICE_DOC
, NULL as BUMPED_PRICE_LC
, NULL as SND_CUST_ALLOW
, NULL as SND_CUST_ALLOW_LC
, NULL as KIT_SND_CUST_ALLOW
, NULL as KIT_SND_CUST_ALLOW_LC
, NULL as SYS_NSP_DOC_PRICE
, NULL as SYS_NSP_CUST_PRICE_LC
, NULL as NSP_DOC_PRICE
, to_char(inv.net_u_price) as NSP_LC
, to_char(inv.net_u_price) as NSP_EUR
, NULL as SND_VENDOR_ALLOW_DC
, NULL as SND_VENDOR_ALLOW_LC
, NULL as PC_PRICE
, NULL as PC_PRICE_LC
, NULL as MAN_PRICING_IND
, NULL as BUMP_VALUE_DOC
, NULL as BUMP_VALUE_LC
, NULL as GOV_FEE_DOC
, NULL as GOV_FEE_LC
, NULL as VELOCITY_DOC
, NULL as VELOCITY_LC
, NULL as INTOUCH_DISCOUNT_DOC
, NULL as INTOUCH_DISCOUNT_LC
, NULL as PC_PRICE_VENDOR_CUR
, NULL as VENDORS_CUR
, NULL as END_CUST_PRICE_REF_LC
, to_char(inv.u_cost) as AC_PRICE
, to_char(inv.u_cost) as AC_PRICE_LC
, NULL as TOTAL_CA_ON_AC_KIT_COMP
, NULL as TOTAL_CA_ON_AC_KIT_COMP_LC
, NULL as TOTAL_CA_ON_AC_KIT_HEADER
, NULL as TOTAL_CA_ON_AC_KIT_HEADER_LC
, NULL as SALES_ADJ_PROFIT
, NULL as SALES_ADJ_PROFIT_LC
, NULL as WEEE_GOV_FEE
, NULL as WEEE_GOV_FEE_LC
, NULL as FUNCTIONAL_DISCOUNT
, NULL as FUNCTIONAL_DISCOUNT_LC
, to_char(inv.order_entry_datetime, 'YYYY-MM-DD') as SALES_ORDER_DATE
, NULL as WARRANTY
, NULL as EDI_ENDCUST_INVOICE
, NULL as UTC_TIME_STAMP
, NULL as SOLD_TO_PARTY_DETAIL
, NULL as MIN_ORDER_SURCHARGE_DC
, NULL as MIN_ORDER_SURCHARGE_LC
, NULL as ACTUAL_VEITY_LC
, NULL as ADD_FREIGHT_TOLLS_DC
, NULL as ADD_FREIGHT_TOLLS_LC
, NULL  as ARCHIVING_DATE
, NULL as PC_PRICE_VENDOR_CUR_SO
, NULL  as PRICING_DATE_SO 
, NULL as BEM_2_DOC
, NULL as BEM_2_LC
, NULL as FREIGHT_COSTS_LC
, NULL as FREIGHT_COSTS_DOC
, NULL as NET_FREIGHT_DOC
, NULL as NET_FREIGHT_LC
, NULL as LOGISTIC_COSTS_DOC
, NULL as LOGISTIC_COSTS_LC
, NULL as FINANCIAL_COSTS_DOC
, NULL as FINANCIAL_COSTS_LC
, NULL as MIN_POM_DOC
, NULL as MIN_POM_LC
, NULL as POCKET_MARGIN_DOC
, NULL as POCKET_MARGIN_LC
, NULL as DIESEL_SURCHARGE_DOC
, NULL as DIESEL_SURCHARGE_LC
, NULL as ADD_POM_FACTOR_DOC
, NULL as ADD_POM_FACTOR_LC
, NULL as COND_ZRET_ASM_BUMP_DOC
, NULL as COND_ZRET_ASM_BUMP_LC
, NULL as FREIGHT_BUMP_ZZ78_DOC
, NULL as FREIGHT_BUMP_ZZ78_LC
, NULL  as COND_DATE
, NULL as COPY_RIGHT_TAX_ZZG9
, NULL as COPY_RIGHT_TAX_ZZG9_LC
, NULL as COND_DATE_SO
, NULL as COND_ZZG6_GOV_FEE_DOC
, NULL as COND_ZZG6_GOV_FEE_LC
, NULL as COND_ZZ94_RETAIL_DISCOUNT_DOC
, NULL as COND_ZZ94_RETAIL_DISCOUNT_LC
, NULL as COND_ZEDI_EDI1_PRICE_DIFF
, NULL as COND_ZEDI_EDI1_PRICE_DIFF_LC
, NULL as COND_ZZ74_ENV_FEE_HEADER
, NULL as COND_ZZ74_ENV_FEE_HEADER_LC
, NULL as VAT_REGISTRATION_NBR
, NULL as TD_VAT_REGISTRATION_NBR
, NULL as ALT_TAX_CLASS
, NULL as TAX_CLASS
, NULL as PROPOSED_MIN_QTY_SURCHARGE
, NULL as ACTUAL_MIN_QTY_SURCHARGE
, NULL as PROPOSED_MIN_QTY_SURCHARGE_LC
, NULL as ACTUAL_MIN_QTY_SURCHARGE_LC
, NULL as SPEC_STOCKPARTN
, NULL as SPEC_STOCKPART_ID
, NULL as DELIVERY_PRIO
, NULL as MATERIAL_TIME_DEPEND
, NULL as MATERIAL_PLANT_TIME_DEPEND
, NULL AS MATERIAL_SALES_TIME_DEPENDL
, NULL as CUST_SALES_TIME_DEPEND
, NULL as INITIAL_PLANT
, NULL as EXPORT_FLAG
, NULL as ORDER_BUCKET_CODE
, NULL as BUSINESS_ORDER_TYPE
, NULL as BUSINESS_ORDER_LVL
, NULL as BASIS_FREIGHT_LC
, NULL as WASHINGTON_STATE_FEE_LC
, NULL as FRONT_END_MARGIN_AC_LC  
, NULL as NET_SALES_MARGIN_AC_LC
, NULL as SALES_ADJ_MARGIN_AC_LC
, NULL as POCKET_MARGIN_AC_LC
, NULL as SELF_FOUNDED_PROMO_LC
, NULL as BASIS_FREIGHT_DOC
, NULL as WASHINGTON_STATE_FEE_DOC
, NULL as FRONT_END_MARGIN_AC_DOC
, NULL as NET_SALES_MARGIN_AC_DOC
, NULL as SALES_ADJ_MARGIN_AC_DOC
, NULL as POCKET_MARGIN_AC_DOC
, NULL as SELF_FOUNDED_PROMO_DOC
, NULL as NBR_PAYMENT_CARD_PLAN
, NULL as OUT_ZONE_FLAG
, NULL as GPMM_MANUAL_PRICE
, NULL as EXTENDED_VENDOR_PURCH_COST_VC
, NULL as EXTENDED_VENDOR_PURCH_COST_LC
, NULL as PC_PRICE_LC_2
, NULL as EXTENDED_VENDOR_PURCH_COST_DC
, NULL as PC_PRICE_DC
, NULL as VENDOR_REBATES_LC
, NULL as VENDOR_REBATES
, NULL as LINE_LVL_SHIP_COND
, NULL as BILL_TO_DETAIL_INFO
, NULL as CUST_DETAILS_INFO
, NULL as NBR_DOC_COND
, NULL as SND_RED_AC_DOC
, NULL as SND_RED_AC_ZZKZWI4_LC
, NULL as HRZN_FRA2_FLAG
, NULL as FREIGHT_ADDER_VALUE_LC
, NULL as IBU_FLAG
, NULL as IBU_ADDER_VALUE_LC
, NULL as ROYALTY_ADDER_FLAG
, NULL as ROYALTY_ADDER_VALUE
, NULL as CUSTOM_FLAG
, NULL as CUSTOME_VALUE_LC
, NULL as ROYALTY_CUR
, NULL as ORIGINAL_BILL_DATE
, NULL as FIXED_VENDOR_SOURCE_LIST
, to_char(month(to_date(inv.date_flag))) as CALENDAR_MONTH
, dt."/BIC/TUCCFQTR" as FISCAL_QUARTER
, NULL as HIGH_LVL_ITEM_SO
, to_char(quarter(to_date(inv.date_flag))) as CALENDAR_QUARTER
, NULL as HIGHER_LVL_DOC_ITEM_NBR
, NULL as BUMP_VOLUME_REB_VAL
, NULL as BUMP_EXCL_VOL_REB
, NULL as CUST_REBATE_VALUE
, NULL as CUST_REBATE_EXCL
, NULL as CUST_REBATE_MDF
, NULL as CUST_REBATE_EXCL_MDF
, NULL as TIME_CREATED
, NULL as BUMP_VOLUME_REB_PERC
, NULL as BUMP_EXCL_VOL_REB_PERC
, NULL as TOTAL_REBATE_BUMP
, NULL as TOTAL_CUST_REBATE
, NULL as BUNDLE_ID
, NULL as BUMPED_BEST_PRICE_DOC
, NULL as BUMPED_BEST_PRICE_LC
, NULL as VENDOR_PROGRAM
, NULL as DAYS_TO_INVOICE
, NULL as PRICING_EXCEPTION_FLAG
, NULL  as POS_REPORTING_DATE
, NULL as DAYS_TO_INVOICE_2
, NULL as SERVICES_SOURCING
, NULL as SERVICES_TECHNOLOGY
, NULL as DND_REASON_NON_EMEA
, NULL as FOREX_CORRECTED_FEM
, NULL as FOREX_CORRECTED_FEP_LC
, NULL as FOREX_CORRECTED_NSM
, NULL as FOREX_CORRECTED_NSP_LC
, NULL as FOREX_CORRECTED_SAM
, NULL as FOREX_CORRECTED_SAP_LC
, NULL as FOREX_CORRECTED_POM
, NULL as FOREX_CORRECTED_POP_LC
, NULL as CUSTS_ACCNT_NBR_CL_REF
, NULL as UPDATE_FLAG
, NULL as FLOORPLAN_SPONSORED_DOC
, NULL as FLOORPLAN_SPONSORED_LC
, NULL as MANUAL_GOV_FEE_DOC
, NULL as MANUAL_GOV_FEE_LC
, NULL as AC_PLUS_INS_TAX_VALUE
, NULL as AC_PLUS_RESELLER_COMMISSION
, NULL as AC_PLUS_VENDOR_COMMISSION
, NULL as AC_PLUS_TD_VENDOR_REBATE
, NULL as AC_PLUS_TD_RESELLER_REBATE
, NULL as AC_PLUS_VENDOR_REBATE_REF
, NULL as INS_SUPPLIER
, NULL as AC_PLUS_INS_TAX_VALUE_LC
, NULL as AC_PLUS_RESELLER_COMMISSION_LC
, NULL as AC_PLUS_VENDOR_COMMISSION_LC
, NULL as DELIVERY_GRP
, NULL as AC_PLUS_INS_PREMIUM_TAX_PERC
, NULL as END_USER_INFO
, NULL as TDM_MDF_ON_INVOICE
, NULL as TDM_MDF_ON_INVOICE_LC
, NULL as TDM_HW_SUBSIDY
, NULL as TDM_HW_SUBSIDY_LC
, NULL as ORIGINAL_SELL_PRICE_
, NULL as ORIGINAL_COST_SUBSCR_LC
, NULL as SUBTOTAL_GOV_FEES
, NULL as SUBTOTAL_GOV_FEES_LC
, NULL as SND_BASE_DP_RATE
, NULL as SND_BASE_DP_RATE_LC
, NULL as RED_FEM_PERC_YAN0
, NULL as RED_FEM_USD_YAN0
, NULL as MINMARG_PERC_YAPB
, NULL as MINMARG_USD_YAPB
, NULL as RED_FEM_PERC_YAN0_LC
, NULL as RED_FEM_USD_YAN0_LC
, NULL as MINMARG_PERC_YAPB_LC
, NULL as MINMARG_USD_YAPB_LC
, NULL as WEB_DISCOUNT_VALUE_LC
, NULL as WEB_DISCOUNT_VALUE
, NULL as TAX_AMOUNT_LC
, NULL as VOUCHER_NBR
, NULL as VOUCHER_VENDOR_ID
, NULL as VOUCHER_VALUE_LC
, NULL as VOUCHER_VALUE_DOC
, NULL as LINE_ORDER_TYPE
, NULL as ORDER_CONSOLIDATION
, NULL as CHEM_FEE_STOCK_HOLDER
, NULL as SPECIAL_STOCK_IND
, NULL as BTO_CUM_VALUE_DOC
, NULL as BAD_BOX_ALLOW_DC
, NULL as BTO_ID
, NULL as INVENTORY_KEY_SALES
, NULL as MATERIAL_TYPE
, NULL as BAD_BOX_ALLOW_LC
, NULL as BTO_CUM_VALUE_LC 
, NULL as SBU_HRCHY_L1_OLD
, inv.date_flag as inv_CALENDAR_DATE 
, NULL as FISCAL_YEAR_VARIANT 
, dt."/BIC/TUCFQYR" as fiscal_year_quarter
, inv.date_flag as BILL_DATE
, concat(year(to_date(inv.date_flag)),week(to_date(inv.date_flag))) as calendar_year_week 
, inv.date_flag as CALENDAR_DAY
, concat(dt.fiscyear, dt."/BIC/TUCCFMTH") as fiscal_year_period
, concat(year(to_date(inv.date_flag)),month(to_date(inv.date_flag))) as calendar_year_month
, to_char(month(to_date(inv.date_flag))) as calendar_month_2
, dt."/BIC/TUCCFMTH" as posting_period
, dt.FISCYEAR as fiscal_year
, to_char(quarter(to_date(inv.date_flag))) as quarter
, concat(year(to_date(inv.date_flag)),quarter(to_date(inv.date_flag))) as calendar_year_quarter
, to_char(year(to_date(inv.date_flag))) as calendar_year
, to_char(from_ref_type) as ELECT_COMMERCE_GRP
, inv.date_flag as BILL_DOC_DATE
, NULL as LOADING_DATE
, to_char(inv.CUST_NAME) as CUST_NAME
, NULL as ACCNT_TYPE
, to_char(inv.MASTER_CUST_NO) as GROUPKEY
, NULL as SBU_HRCHY_L0
, NULL as SBU_HRCHY_L1
, NULL as SBU_HRCHY_L2
, NULL as SBU_HRCHY_L3
, NULL as SBU_HRCHY_L4
, NULL as SBU_HRCHY_L1_TXT
, NULL as SBU_HRCHY_L2_TXT
, NULL as SBU_HRCHY_L3_TXT
, NULL as SBU_HRCHY_L4_TXT
, to_char(pc.SOLUTION_CODE) as TM1_HRCHY_L1
, to_char(pc.LEVEL_1_SEG_ID) as TM1_HRCHY_L2
, to_char(pc.LEVEL_2_SEG_ID) as TM1_HRCHY_L3
, to_char(pc.LEVEL_3_SEG_ID) as TM1_HRCHY_L4
, to_char(inv.UNIVERSAL_VEND_NAME) as GLBL_MFR
, to_char(inv.FAMILY) as PROD_FAMILY
, to_char(inv.CATEGORY) as PROD_CLASS
, to_char(matl.SUB_CATEGORY) as PROD_SUBCLASS
,'US01' AS LEGACY_SALES_ORG
, SYSDATE() as UPDATE_DATE_UTC 
from {{ source('us_cdp_cis_us','DWD_DISTY_COMMON_SALES_DETAIL_DI_US') }}   inv
--from ANALYTICS.EDW_CIS_US.DWD_DISTY_COMMON_SALES_DETAIL_DI_US   inv
left join {{ source('us_cdp_cis_us','DM_PUB_PART_INFO_VIEW_US') }}   matl
--left join ANALYTICS.EDW_CIS_US.DM_PUB_PART_INFO_VIEW_US   matl
  on inv.sku_no = matl.sku_no 
left join {{ source('us_cdp_cis_us','DIM_PUB_BIZ_SEGMENT_HIERARCHY_US') }}  pc
--left join ANALYTICS.EDW_CIS_US.DIM_PUB_BIZ_SEGMENT_HIERARCHY_US  pc
  on matl.vpl_no = pc.vpl_no
left join {{ source('us_cdp_cis_us','DIM_PUB_CUSTOMER_INFO_VIEW_US') }}  cust
--left join ANALYTICS.EDW_CIS_US.DIM_PUB_CUSTOMER_INFO_VIEW_US  cust
  on inv.cust_no = cust.cust_no
left join {{ source('us_cdp_cis_us','DWD_DISTY_COMMON_SALES_EU_DETAIL_DI_US') }} eu
--left join ANALYTICS.EDW_CIS_US.DWD_DISTY_COMMON_SALES_EU_DETAIL_DI_US eu
  on inv.order_no = eu.order_no
  and inv.order_line_no = eu.order_line_no
  and inv.order_type = eu.order_type
left join  {{ source('us_cdp_bw_46','TUCTCDAYS') }}  dt
--left join  ANALYTICS.EDW_SAP_BW_US_46.TUCTCDAYS  dt
  on to_char(inv.date_flag) = dt."/BIC/TUCTCDAYS"
  and dt."/BIC/TUCCOMPCE" = '0100'
  and dt."FISCVARNT" = 'Z1'


