{{
    config(
        alias = 'material_master',
        materialized = 'table'

    )
}}


with t6 as (select distinct t1."/BIC/TUCMATERL"
            from {{ source('us_cdp_bw_46','TUCMATERL') }}  as t1 
            left join {{ source('us_cdp_bw_46','TUCMATSAS') }}  as t3 
              on t1."/BIC/TUCMATERL" = t3."/BIC/TUCMATSAS" 
            and t1.SOURSYSTEM = t3.SOURSYSTEM 
            and t1.OBJVERS = t3.OBJVERS
            and t3."/BIC/TUCDISTRN" = '00'
          where (t3."/BIC/TUCVMSTA" = '' 
              or t3."/BIC/TUCVMSTA" is null 
              or t3."/BIC/TUCVMSTA" < 70) 
             and t3."/BIC/TUCINT65" = '' 
             and t3."/BIC/TUCINT01" = '')


select 
md5(concat(t1.SOURSYSTEM,t1."/BIC/TUCMATERL",nvl(t3."/BIC/TUCSALESG",''),nvl(t3."/BIC/TUCDISTRN",''))) as material_master_key,
t1.SOURSYSTEM as SOURSYSTEM,
t1."/BIC/TUCMATERL" as MATERIAL_ID,
t1.OBJVERS as OBJECT_VERSION,
nvl(t3."/BIC/TUCSALESG",'') as SALES_ORG,
nvl(t3."/BIC/TUCDISTRN",'') as DISTR_CHANNEL,
t3."/BIC/TUCMATSAS" as MATERIAL_OD_SALES,
t1.LOGSYS as SOURCE_SYSTEM,
t1."/BIC/TUCACTC" as ACTIVE_FLAG,
t1."/BIC/TUCAESZNN" as UN_NBR_NA,
t1."/BIC/TUCARCH" as ARCHIVE__FLAG,
t1."/BIC/TUCBUNDFL" as MATERIAL_IS_BUNDLE,
t1."/BIC/TUCCNETL1" as CNET_LVL_1,
t1."/BIC/TUCCNETL2" as CNET_LVL_2,
t1."/BIC/TUCCNETL3" as CNET_LVL_3,
t1."/BIC/TUCCNETL4" as CNET_LVL_4,
t1."/BIC/TUCCNETL5" as CNET_LVL_5,
t1."/BIC/TUCCNETL6" as CNET_LVL_6,
t1."/BIC/TUCCNETL7" as CNET_LVL_7,
t1."/BIC/TUCCNETL8" as TCNET_LVL_8,
t1."/BIC/TUCCOMCHA" as COMPUTER_CHANNEL,
t1."/BIC/TUCCOMPER" as COMPETITORS,
t1."/BIC/TUCDELFLG" as DELETION_FLAG,
t1."/BIC/TUCDIVISN" as DIVISION,
t1."/BIC/TUCEANUPC" as EUROPEAN_ARTICLE_NBR,
t1."/BIC/TUCEKWSL"  as  PURCHASING_VALUE_KEY,
t1."/BIC/TUCEXTMAP" as EXTERNAL_MATERIAL_GRP ,
t1."/BIC/TUCFAMILY" as PROD_FAMILY,
t1."/BIC/TUCGLGMNA" as GOALING_GLBL_MFR,
t1."/BIC/TUCHAZFLG" as HAZARDOUS_MATERIAL,
t1."/BIC/TUCHORS0"  as  HRZN_LOC_FIELD_S0,
t1."/BIC/TUCHORS1"  as  HRZN_LOC_FIELD_S1,
NULL as HRZN_LOC_FIELD_S10,
NULL as HRZN_LOC_FIELD_S11,
NULL as HRZN_LOC_FIELD_S12,
NULL as HRZN_LOC_FIELD_S13,
NULL as HRZN_LOC_FIELD_S14,
NULL as HRZN_LOC_FIELD_S15,
NULL as HRZN_LOC_FIELD_S16,
NULL as HRZN_LOC_FIELD_S17,
NULL as HRZN_LOC_FIELD_S18,
NULL as HRZN_LOC_FIELD_S19,
NULl  as HRZN_LOC_FIELD_S2,
NULL as HRZN_LOC_FIELD_S20,
NULL as HRZN_LOC_FIELD_S21,
NULL as HRZN_LOC_FIELD_S22,
NULL as HRZN_LOC_FIELD_S23,
NULL as HRZN_LOC_FIELD_S24,
NULL as TM1_VENDOR,
NULL as HRZN_LOC_FIELD_S26,
NULL as HRZN_LOC_FIELD_S27,
NULL as HRZN_LOC_FIELD_S3,
NULL as HRZN_LOC_FIELD_S4,
NULL as HRZN_LOC_FIELD_S5,
NULL as HRZN_LOC_FIELD_S6,
NULL as HRZN_LOC_FIELD_S7,
NULL as HRZN_LOC_FIELD_S8,
NULL as HRZN_LOC_FIELD_S9,
t1."/BIC/TUCINDSER" as INDUSTRY_SECTOR,
t1."/BIC/TUCINT58" as NO_CNET,
t1."/BIC/TUCLDPRLH" as CLOUD_PRODLH,
t1."/BIC/TUCMAFL" as TS_TD_COMMON_MATERIAL,
t1."/BIC/TUCMANDE" as MFR_DESCRIPTION,
t1."/BIC/TUCMANUMR" as MFR_PART_NBR,
t1."/BIC/TUCMATLCT" as MATERIAL_CTGRY,
t1."/BIC/TUCMATLGP" as MATERIAL_GRP ,
t1."/BIC/TUCMATLTE" as MATERIAL_TYPE,
t1."/BIC/TUCMMATN" as MFR_PART_NBR_CLEANED,
t1."/BIC/TUCMSTAE" as CROSS_PLANT_MATERIAL,
t1."/BIC/TUCMUPACK" as MULTI_PACK_NBR,
t1."/BIC/TUCNSTRSO" as NEW_STRATEGIC_SOLUTION,
t1."/BIC/TUCPROD" as PROD_CLASS,
t1."/BIC/TUCPRODHR" as PROD_HRCHY,
t1."/BIC/TUCPRSTM1" as PROD_SERVICE,
t1."/BIC/TUCSIZEDM" as SIZE_DIMENSION,
t1."/BIC/TUCSLCTM1" as SOLUTION_CTGRY,
t1."/BIC/TUCSLPTM1" as SOLUTION_PORTFOLIO,
t1."/BIC/TUCSUB" as PROD_SUBCLASS,
t1."/BIC/TUCTSMAT" as TS_MATERIAL,
t1."/BIC/TUCVEPAOE" as VENDOR_PART_NBR_EXTENSION,
t1."/BIC/TUCVEPARO" as VENDOR_PART_NBR,
t1."/BIC/TUCWFAMIL" as WW_FAMILY_NAME,
t1."/BIC/TUCWPROD" as WW_CLASS_NAME,
t1."/BIC/TUCZHPPH1" as HP_PROD_HRCHY_LVL_1,
t1."/BIC/TUCZHPPH2" as HP_PROD_HRCHY_LVL_2,
t1."/BIC/TUCZHPPH3" as HP_PROD_HRCHY_LVL_3,
t1."/BIC/TUCZHPPH4" as HP_PROD_HRCHY_LVL_4,

case
 when t1."/BIC/TUCZZGMNR" = 'SERVICE' then nvl(t3."/BIC/TUCZZLMNR", 'SERVICE') 
  else nvl(t5.vendor_cis, t1."/BIC/TUCZZGMNR")
end as GLBL_MFR,

t1."/BIC/TUDCHONN" as LAST_CHANGED_ON,
t1."/BIC/TUDCREATN" as CREATION_DATE,
t1."/BIC/TUDMSTDEE" as CROSS_PLANT_MAT_VALID ,
t1."/BIC/TUDTANLLH" as DATA_ANALYTICS_LH,
t1."/BIC/TUDTCNTLH" as DATA_CENTER_LH,
t1."/BIC/TUIOTLH" as IOT_LH,
t1."/BIC/TUKESTGR" as ESTIMATE_GROSS_WEIGT,
t1."/BIC/TUKGROSWT" as GROSS_WEIGHT,
t1."/BIC/TUKHEIGHT" as HEIGHT,
t1."/BIC/TUKHORN1" as HRZN_LOC_FIELD_N1,
NULL as HRZN_LOC_FIELD_N10,
NULL as HRZN_LOC_FIELD_N11,
NULL as HRZN_LOC_FIELD_N12,
NULL as HRZN_LOC_FIELD_N13,
NULL as HRZN_LOC_FIELD_N14,
NULL as HRZN_LOC_FIELD_N15,
NULL as HRZN_LOC_FIELD_N16,
NULL as HRZN_LOC_FIELD_N17,
NULL as HRZN_LOC_FIELD_N18,
NULL as HRZN_LOC_FIELD_N19,
NULL as HRZN_LOC_FIELD_N2,
NULL as HRZN_LOC_FIELD_N20,
NULL as HRZN_LOC_FIELD_N21,
NULL as HRZN_LOC_FIELD_N22,
NULL as HRZN_LOC_FIELD_N23,
NULL as HRZN_LOC_FIELD_N24,
NULL as HRZN_LOC_FIELD_N25,
NULL as HRZN_LOC_FIELD_N26,
NULL as HRZN_LOC_FIELD_N27,
NULL as HRZN_LOC_FIELD_N28,
NULL as HRZN_LOC_FIELD_N29,
NULL as  HRZN_LOC_FIELD_N3,
NULL as  HRZN_LOC_FIELD_N4,
NULL as  HRZN_LOC_FIELD_N5,
NULL as  HRZN_LOC_FIELD_N6,
NULL as  HRZN_LOC_FIELD_N7,
NULL as  HRZN_LOC_FIELD_N8,
NULL as  HRZN_LOC_FIELD_N9,
NULL as  HRZN_LOC_FIELD_N0,
t1."/BIC/TUKLENGHT" as LENGTH,
t1."/BIC/TUKNETWET" as WEIGHT,
t1."/BIC/TUKVOLUME" as VOLUME,
t1."/BIC/TUKWIDTHH" as WIDTH ,
t1."/BIC/TUMOBILH" as MOBILITY_LH,
t1."/BIC/TUSECURLH" as SECURITY_LH,
t1."/BIC/TUTREDULH" as TRAINING_EDUCATION_LH,
t1."/BIC/TUUBASEUM" as BASE_UNIT_OF_MEASURE,
t1."/BIC/TUUCONTUT" as CONTENT_UNIT,
t1."/BIC/TUUPOUNIT" as ORDER_UNIT,
t1."/BIC/TUUUNITDM" as UNIT_LENGTH_WDTH_HEIGHT,
t1."/BIC/TUUUNITOT" as WEIGHT_UNIT,
t1."/BIC/TUUVOLUMT" as VOLUME_UNIT,
t3."/BIC/TUCAOANR" as OLD_ARTICLE_NBR_40,
t3."/BIC/TUCARCH" as ARCHIVE_FLAG_SS,
t3."/BIC/TUCCKONDM" as CALC_MAT_PRICING_GRP,
t3."/BIC/TUCDELFLG" as DELETION_FLAG_SS,
t3."/BIC/TUCDNDRE" as DND_REASON ,
t3."/BIC/TUCDWERK" as DELIVERING_PLANT,
t3."/BIC/TUCECCGR" as ECC_PROD_GRP,
t3."/BIC/TUCFORCAT" as MRP_FORECASTER,
t3."/BIC/TUCFRTP" as NO_FREIGHT_3RD_PARTY,
t3."/BIC/TUCH032" as EC_DO_NOT_DISPLAY_IR,
t3."/BIC/TUCH794" as HRZN_REWORK_BUNDLING,
t3."/BIC/TUCHCL108" as GLBL_CLOUD_FLAG_108,
t3."/BIC/TUCHCL62F" as HRZN_CLOUD_62_FLAG,
t3."/BIC/TUCHCOSET" as HRZN_COPY_SETTING,
t3."/BIC/TUCHM1447" as HRZN_MOB_DEVICE_ACTIVATION,
t3."/BIC/TUCHORS0" as HRZN_LOC_FIELD_S0_SS,
t3."/BIC/TUCHORS1" as HRZN_LOC_FIELD_S1_SS,
t3."/BIC/TUCHORS2" as HRZN_LOC_FIELD_S2_SS,
t3."/BIC/TUCHORS3" as HRZN_LOC_FIELD_S3_SS,
t3."/BIC/TUCHORS4" as HRZN_LOC_FIELD_S4_SS,
t3."/BIC/TUCHORS5" as HRZN_LOC_FIELD_S5_SS,
t3."/BIC/TUCHORS6" as HRZN_LOC_FIELD_S6_SS,
t3."/BIC/TUCHORS7" as HRZN_LOC_FIELD_S7_SS,
t3."/BIC/TUCHORS8" as HRZN_LOC_FIELD_S8_SS,
t3."/BIC/TUCHORS9" as HRZN_LOC_FIELD_S9_SS,
t3."/BIC/TUCIAUTRE" as AUTOTDESK_RECUR_PROD,
t3."/BIC/TUCINT01" as EC_DO_NOT_DISPLAY,
t3."/BIC/TUCINT031" as EC_NOT_ORDERABLE_IR,
NULL as MAINTENANCE_FY19_REV,
NULL as INTOUCH_104_HP_WARRANTY,
NULL as ENT_LIC_AGRMT_FY19_REV,
NULL as ANTIVIRUS_SECUR_FY19_REV,
t3."/BIC/TUCINT123" as SW_BUNDLES_FY19_REV,
t3."/BIC/TUCINT13" as CONFORMITY_FLAG_HRZN,
NULL as PL_ACTIVE_FLAG_HRZN,
t3."/BIC/TUCINT37" as HP_ECAREPACK,
t3."/BIC/TUCINT401" as EC_DO_NOT_DISPLAY_UK,
t3."/BIC/TUCINT403" as EC_NOT_ORDERABLE_UK,
t3."/BIC/TUCINT47" as HRZN_FLAG_47,
t3."/BIC/TUCINT50" as HOT_SKU,
t3."/BIC/TUCINT55" as EC_ALLOC_FLAG_HRZN,
t3."/BIC/TUCINT56" as EC_NO_TAKING_BACK_HRZN,
t3."/BIC/TUCINT57" as CNET_FLAG_NOT_USED,
t3."/BIC/TUCINT61" as EC_APPLE_CARE_PLAN,
t3."/BIC/TUCINT63" as MS_TOUCHWINS_DEVICE,
t3."/BIC/TUCINT65" as EC_DO_NOT_DISPLAY_INTOUCH,
NULL as EC_GAMING,
t3."/BIC/TUCINT73" as EDI_BLOCK,
t3."/BIC/TUCINT81" as DELL_WARRANTY,
t3."/BIC/TUCINT96" as EC_AUTHORIZED_CUST,
t3."/BIC/TUCINT98" as EC_CUST_SPECIFIC,
t3."/BIC/TUCINTANL" as HRZN_FLAG_ANALYTICS,
t3."/BIC/TUCINTCTR" as HRZN_FLAG_DATA_CENT,
t3."/BIC/TUCINTEDU" as HRZN_FLAG_EDUCATION,
t3."/BIC/TUCINTIOT" as IOT_FLAG,
t3."/BIC/TUCINTMOB" as HRZN_FLAG_MOBILITY,
t3."/BIC/TUCINTNON" as HRZN_FLAG_NON_TUCHN,
t3."/BIC/TUCINTSEC" as HRZN_FLAG_SECURITY,
t3."/BIC/TUCKTGRM" as ACCNT_ASSIGN_GRP,
t3."/BIC/TUCMATLG1" as BUSINESS_MANAGER,
t3."/BIC/TUCMATLG2" as DIVISION_MANAGER,
t3."/BIC/TUCMATLG3" as DIRECTOR,
t3."/BIC/TUCMATLG4" as REPAIR_TIME_DAYS,
t3."/BIC/TUCMATLG5" as INVESTIGATION_RESULT,
t3."/BIC/TUCMTPOS" as ITEM_CTGRY_GRP,
t3."/BIC/TUCOANR" as OLD_ARTICLE_NBR,
t3."/BIC/TUCPABC" as MATERIAL_PRICING_GRP,
t3."/BIC/TUCPFLAG" as PRICING_FLAG_HRZN,
t3."/BIC/TUCPRAT1" as PROMO_FLAG,
t3."/BIC/TUCPRAT2M" as RECYCLING_FEE,
t3."/BIC/TUCPRAT3M" as EDI_BLOCK_2,
NULL as SND_CLAIM_SERIAL_NBR,
t3."/BIC/TUCPRAT4M" as SND_FLAG ,
t3."/BIC/TUCPRAT5M" as CUST_REBATE_EXCLUSIVE,
t3."/BIC/TUCPRAT7M" as EU_REQUIRED_FLAG,
t3."/BIC/TUCPRAT8M" as LARGE_DIMENSION_PROD,
t3."/BIC/TUCPRATA" as AUTODESK_MULTI_SEAT,
t3."/BIC/TUCPRDHI1" as L_PROD_HRCHY_PART_1,
t3."/BIC/TUCPRDHI2" as L_PROD_HRCHY_PART_2,
t3."/BIC/TUCPRDHI3" as L_PROD_HRCHY_PART_3,
t3."/BIC/TUCPRODHR" as  PROD_HRCHY_SS,
t3."/BIC/TUCRATE" as HRZN_VAT_RATE_SALES,
t3."/BIC/TUCREBATP" as  VOLUME_REBATE_GRP,
t3."/BIC/TUCSALNOT" as SALES_NOTICE,
t3."/BIC/TUCSAOABC" as SALES_ORG_ABC,
t3."/BIC/TUCSPHAI" as SPECIAL_HANDLING_IND,
t3."/BIC/TUCTDFPOE" as TDIT_FREIGHT_POLICY,
t3."/BIC/TUCTFORCA" as TDIT_FORECASTER,
t3."/BIC/TUCVALP" as VALIDITY_PERIOD_MNTH,
t3."/BIC/TUCVMSTA" as SALES_BLOCK_DISTR_CHAIN ,
t3."/BIC/TUCWRRNT" as WARRANTY_CODE,
t3."/BIC/TUCYVENPL" as VENDOR_PROD_LINE,
t3."/BIC/TUCZZLMNR" as LOC_MFR ,
t3."/BIC/TUDCHONN" as LAST_CHANGED_ON_SS,
t3."/BIC/TUDCONVFF" as CONFORMITY_VALID_FROM,
t3."/BIC/TUDCREATN" as CREATION_DATE_SS,
t3."/BIC/TUDDNDEXP" as DND_EXPIRY_DATE,
t3."/BIC/TUDLSODAT" as LAST_SO_DATE,
NULL as  PL_ACTIVE_VALID_FROM_HRZN,
t3."/BIC/TUDVMSTDD" as DISTR_CHAIN_VALIDITY_DATE,
t3."/BIC/TUKAAGE" as AVERAGE_ARTICLE_AGE,
t3."/BIC/TUKHORN1" as HRZN_LOC_FIELD_N1_SS,
t3."/BIC/TUKHORN2" as HRZN_LOC_FIELD_N2_SS,
t3."/BIC/TUKHORN3" as HRZN_LOC_FIELD_N3_SS,
t3."/BIC/TUKHORN4" as HRZN_LOC_FIELD_N4_SS,
t3."/BIC/TUKHORN5" as HRZN_LOC_FIELD_N5_SS,
t3."/BIC/TUKHORN6" as HRZN_LOC_FIELD_N6_SS,
t3."/BIC/TUKHORN7" as HRZN_LOC_FIELD_N7_SS,
t3."/BIC/TUKHORN8" as HRZN_LOC_FIELD_N8_SS,
t3."/BIC/TUKHORN9" as HRZN_LOC_FIELD_N9_SS,
t3."/BIC/TUKHORNO" as HRZN_LOC_FIELD_N0_SS,
t3."/BIC/TUKPRMAC" as AC_ADJ_COST_MASTERDATA,
t3."/BIC/TUKPRMDP" as DP_DEALER_PRICE_MASTERDATA,
t3."/BIC/TUKPRMLP" as LP_ADJ_COST_MASTERDATA,
t3."/BIC/TUKPRMPC" as PC_ADJ_COST_MASTERDATA,
t3."/BIC/TUUBASEUM" as BASE_UNIT_OF_MEASURE_SS,
t3."/BIC/TUYKONACC" as RATE_UNIT_AC,
t3."/BIC/TUYKONDPP" as RATE_UNIT_DP,
t3."/BIC/TUYKONLPP" as RATE_UNIT_LP,
t3."/BIC/TUYKONPCC" as RATE_UNIT_PC,
NULL as GM_MFR_PART_NBR,
NULL as GM_MFR_NAME,
NULL as GM_LONG_PROD_DESCRIPTION,
NULL as GM_PRODTEXT_SAP,
NULL as GM_SHORT_DESCRIPTION,
NULL as GM_TRADE_PRICE,
NULL as GM_ITEM_CTGRY_GRP,
NULL as GM_RRP,
NULL as GM_NBR_PRODS_IN_STOCK,
NULL as GM_STOCK_DELIVERY_DATE,
NULL as GM_PROD_WEIGHT,
NULL as GM_PICTURE_URL,
NULL as GM_F32,

case 
  when (t3."/BIC/TUCVMSTA" = '' 
     or t3."/BIC/TUCVMSTA" is null 
     or t3."/BIC/TUCVMSTA" < 70) 
     and t3."/BIC/TUCINT65" = '' 
     and t3."/BIC/TUCINT01" = '' 
    then true 
  else false 
end as COUNTRY_LVL_ACTIVITY,

case 
  when t6."/BIC/TUCMATERL" is not null then true 
  else false
end as MATERIAL_LVL_ACTIVITY,

SYSDATE() as UPDATE_DATE_UTC,
NULL as ADVANCED_SOLUTIONS_SALES_ORG,
'4.6' AS ORIGINAL_SOURCE
from {{ source('us_cdp_bw_46','TUCMATERL') }}  as t1 
join {{ source('us_cdp_bw_46','TUCMATSAS') }} as t3 
  on t1."/BIC/TUCMATERL" = t3."/BIC/TUCMATSAS"
  and t1.SOURSYSTEM = t3.SOURSYSTEM
  --and t1.soursystem = 'A3'
  and  t3."/BIC/TUCDISTRN" = '00'    

left join t6
  on t1."/BIC/TUCMATERL" = t6."/BIC/TUCMATERL"

left join {{ source('us_cdp','GLBL_MFR_TO_VENDOR_CIS_MAPPING_VIEW')}} t5
  on t1."/BIC/TUCZZGMNR" = t5.GLBL_MFR
-- part 2 6.8

UNION ALL 
 
select 
md5(concat(t1.SOURSYSTEM,t1."/BIC/TNMATERIL", t4."/BIC/TNSALEORG" ,nvl(t4."/BIC/TNDISTNCH",''))) as material_master_key,
t1.SOURSYSTEM as SOURSYSTEM,
t1."/BIC/TNMATERIL" as MATERIAL_ID,
t1.objvers as OBJECT_VERSION,
t4."/BIC/TNSALEORG" as SALES_ORG, 
nvl(t4."/BIC/TNDISTNCH",'') as DISTR_CHANNEL,
t4."/BIC/TNMATSLS" as MATERIAL_OD_SALES,
NULL as SOURCE_SYSTEM,
t1."/BIC/TNMATACFL" as ACTIVE_FLAG,
NULL as UN_NBR_NA ,
NULL as ARCHIVE__FLAG,
NULL as MATERIAL_IS_BUNDLE,
NULL as CNET_LVL_1,
NULL as CNET_LVL_2,
NULL as CNET_LVL_3,
NULL as CNET_LVL_4,
NULL as CNET_LVL_5,
NULL as CNET_LVL_6,
NULL as CNET_LVL_7,
NULL as CNET_LVL_8,
NULL as COMPUTER_CHANNEL,
NULL as COMPETITORS,
NULL as DELETION_FLAG,
NULL as DIVISION ,
NULL as EUROPEAN_ARTICLE_NBR,
NULL as PURCHASING_VALUE_KEY,
NULL as EXTERNAL_MATERIAL_GRP,
NULL as PROD_FAMILY,
NULL as GOALING_GLBL_MFR,
NULL as HAZARDOUS_MATERIAL,
NULL as HRZN_LOC_FIELD_S0,
NULL as HRZN_LOC_FIELD_S1,
NULL as HRZN_LOC_FIELD_S10,
NULL as HRZN_LOC_FIELD_S11,
NULL as HRZN_LOC_FIELD_S12,
NULL as HRZN_LOC_FIELD_S13,
NULL as HRZN_LOC_FIELD_S14,
NULL as HRZN_LOC_FIELD_S15,
NULL as HRZN_LOC_FIELD_S16,
NULL as HRZN_LOC_FIELD_S17,
NULL as HRZN_LOC_FIELD_S18,
NULL as HRZN_LOC_FIELD_S19,
NULL as HRZN_LOC_FIELD_S2,
NULL as HRZN_LOC_FIELD_S20,
NULL as HRZN_LOC_FIELD_S21,
NULL as HRZN_LOC_FIELD_S22,
NULL as HRZN_LOC_FIELD_S23,
NULL as HRZN_LOC_FIELD_S24,
NULL as TM1_VENDOR,
NULL as HRZN_LOC_FIELD_S26,
NULL as HRZN_LOC_FIELD_S27,
NULL as HRZN_LOC_FIELD_S3,
NULL as HRZN_LOC_FIELD_S4,
NULL as HRZN_LOC_FIELD_S5,
NULL as HRZN_LOC_FIELD_S6,
NULL as HRZN_LOC_FIELD_S7,
NULL as HRZN_LOC_FIELD_S8,
NULL as HRZN_LOC_FIELD_S9,
NULL as INDUSTRY_SECTOR ,
NULL as NO_CNET,
NULL as CLOUD_PRODLH ,
NULL as TS_TD_COMMON_MATERIAL,
NULL as MFR_DESCRIPTION,
t1."/BIC/TNMFR_MAT" as MFR_PART_NBR,
NULL as MATERIAL_CTGRY,
NULL as MATERIAL_GRP,
t1."/BIC/TNMATLTYP" as MATERIAL_TYPE,
NULL as MFR_PART_NBR_CLEANED,
NULL as CROSS_PLANT_MATERIAL,
NULL as MULTI_PACK_NBR,
NULL as NEW_STRATEGIC_SOLUTION,
NULL as PROD_CLASS,
NULL as PROD_HRCHY,
NULL as PROD_SERVICE,
NULL as SIZE_DIMENSION ,
NULL as SOLUTION_CTGRY,
NULL as SOLUTION_PORTFOLIO,
NULL as PROD_SUBCLASS,
NULL as TS_MATERIAL,
NULL as VENDOR_PART_NBR_EXTENSION,
NULL as VENDOR_PART_NBR,
NULL as WW_FAMILY_NAME,
NULL as WW_CLASS_NAME,
t1."/BIC/TNPRODH1" as HP_PROD_HRCHY_LVL_1,
NULL as HP_PROD_HRCHY_LVL_2,
NULL as HP_PROD_HRCHY_LVL_3,
NULL as HP_PROD_HRCHY_LVL_4, 
nvl(cis_map.vendor_cis, mfg_map.glbl_mfr) as GLBL_MFR,
NULL as  LAST_CHANGED_ON,
t1.createdon as CREATION_DATE,
NULL as CROSS_PLANT_MAT_VALID,
NULL as DATA_ANALYTICS_LH ,
NULL as DATA_CENTER_LH,
NULL as IOT_LH,
NULL as ESTIMATE_GROSS_WEIGT,
NULL as GROSS_WEIGHT,
NULL as HEIGHT,
NULL as  HRZN_LOC_FIELD_N1 ,
NULL as HRZN_LOC_FIELD_N10,
NULL as HRZN_LOC_FIELD_N11,
NULL as HRZN_LOC_FIELD_N12,
NULL as HRZN_LOC_FIELD_N13,
NULL as HRZN_LOC_FIELD_N14,
NULL as HRZN_LOC_FIELD_N15,
NULL as HRZN_LOC_FIELD_N16,
NULL as HRZN_LOC_FIELD_N17,
NULL as HRZN_LOC_FIELD_N18,
NULL as HRZN_LOC_FIELD_N19,
NULL as HRZN_LOC_FIELD_N2,
NULL as HRZN_LOC_FIELD_N20,
NULL as HRZN_LOC_FIELD_N21,
NULL as HRZN_LOC_FIELD_N22,
NULL as HRZN_LOC_FIELD_N23,
NULL as HRZN_LOC_FIELD_N24,
NULL as HRZN_LOC_FIELD_N25,
NULL as HRZN_LOC_FIELD_N26,
NULL as HRZN_LOC_FIELD_N27,
NULL as HRZN_LOC_FIELD_N28,
NULL as HRZN_LOC_FIELD_N29,
NULL as HRZN_LOC_FIELD_N3,
NULL as HRZN_LOC_FIELD_N4,
NULL as HRZN_LOC_FIELD_N5,
NULL as HRZN_LOC_FIELD_N6,
NULL as HRZN_LOC_FIELD_N7,
NULL as HRZN_LOC_FIELD_N8,
NULL as HRZN_LOC_FIELD_N9,
NULL as HRZN_LOC_FIELD_N0,
NULL as LENGTH ,
NULL as WEIGHT,
NULL as VOLUME,
NULL as WIDTHH,
NULL as MOBILITY_LH,
NULL as SECURITY_LH,
NULL as TRAINING_EDUCATION_LH,
NULL as BASE_UNIT_OF_MEASURE,
NULL as CONTENT_UNIT,
NULL as ORDER_UNIT,
NULL as UNIT_LENGTH_WDTH_HEIGHT ,
NULL as WEIGHT_UNIT,
NULL as VOLUME_UNIT,
NULL as OLD_ARTICLE_NBR_40,
NULL as ARCHIVE_FLAG_SS,
NULL as CALC_MAT_PRICING_GRP,
NULL as DELETION_FLAG_SS,
NULL as DND_REASON,
NULL as DELIVERING_PLANT,
NULL as ECC_PROD_GRP,
NULL as ECC_PROD_CAT,
NULL as NO_FREIGHT_3RD_PARTY,
NULL as NO_FREIGHT_3RD_PARTY,
NULL as HRZN_REWORK_BUNDLING,
NULL as GLBL_CLOUD_FLAG_108,
NULL as HRZN_CLOUD_62_FLAG,
NULL as HRZN_COPY_SETTING,
NULL as HRZN_MOB_DEVICE_ACTIVATION,
NULL as HRZN_LOC_FIELD_S0_SS,
NULL as HRZN_LOC_FIELD_S1_SS,
NULL as HRZN_LOC_FIELD_S2_SS,
NULL as HRZN_LOC_FIELD_S3_SS,
NULL as HRZN_LOC_FIELD_S4_SS,
NULL as HRZN_LOC_FIELD_S5_SS,
NULL as HRZN_LOC_FIELD_S6_SS,
NULL as HRZN_LOC_FIELD_S7_SS,
NULL as HRZN_LOC_FIELD_S8_SS,
NULL as HRZN_LOC_FIELD_S9_SS,
NULL as  AUTOTDESK_RECUR_PROD,
NULL as EC_DO_NOT_DISPLAY,
NULL as EC_NOT_ORDERABLE_IR,
NULL as MAINTENANCE_FY19_REV,
NULL as INTOUCH_104_HP_WARRANTY,
NULL as ENT_LIC_AGRMT_FY19_REV,
NULL as ANTIVIRUS_SECUR_FY19_REV,
NULL as SW_BUNDLES_FY19_REV,
NULL as CONFORMITY_FLAG_HRZN,
NULL as PL_ACTIVE_FLAG_HRZN,
NULL as HP_ECAREPACK,
NULL as EC_DO_NOT_DISPLAY_UK,
NULL as EC_NOT_ORDERABLE_UK,
NULL as HRZN_FLAG_47,
NULL as HOT_SKU,
NULL as EC_ALLOC_FLAG_HRZN,
NULL as EC_NO_TAKING_BACK_HRZN,
NULL as CNET_FLAG_NOT_USED,
NULL as EC_APPLE_CARE_PLAN,
NULL as MS_TOUCHWINS_DEVICE,
NULL as EC_DO_NOT_DISPLAY_INTOUCH ,
NULL as EC_GAMING,
NULL as EDI_BLOCK,
NULL as DELL_WARRANTY,
NULL as EC_AUTHORIZED_CUST,
NULL as EC_CUST_SPECIFIC,
NULL as HRZN_FLAG_ANALYTICS,
NULL as HRZN_FLAG_DATA_CENT,
NULL as HRZN_FLAG_EDUCATION,
NULL as IOT_FLAG,
NULL as HRZN_FLAG_MOBILITY,
NULL as HRZN_FLAG_NON_TUCHN ,
NULL as HRZN_FLAG_SECURITY,
t4."/BIC/TNMTKTGRM" as ACCNT_ASSIGN_GRP,
NULL as BUSINESS_MANAGER,
NULL as DIVISION_MANAGER,
NULL as DIRECTOR,
NULL as REPAIR_TIME_DAYS ,
NULL as INVESTIGATION_RESULT,
NULL as ITEM_CTGRY_GRP,
NULL as OLD_ARTICLE_NBR,
NULL as MATERIAL_PRICING_GRP,
NULL as PRICING_FLAG_HRZN,
NULL as PROMO_FLAG,
NULL as RECYCLING_FEE,
NULL as EDI_BLOCK_2,
NULL as SND_CLAIM_SERIAL_NBR,
NULL as SND_FLAG,
NULL as CUST_REBATE_EXCLUSIVE,
NULL as EU_REQUIRED_FLAG,
NULL as LARGE_DIMENSION_PROD,
NULL as AUTODESK_MULTI_SEAT,
NULL as L_PROD_HRCHY_PART_1,
NULL as L_PROD_HRCHY_PART_2,
NULL as L_PROD_HRCHY_PART_3,
t4."/BIC/TNPRODHIE" as PROD_HRCHY_SS,
NULL as HRZN_VAT_RATE_SALES,
NULL as TVOLUME_REBATE_GRP,
NULL as SALES_NOTICE,
NULL as SALES_ORG_ABC,
NULL as SPECIAL_HANDLING_IND,
NULL as TDIT_FREIGHT_POLICY ,
NULL as TDIT_FORECASTER,
NULL as VALIDITY_PERIOD_MNTH,
NULL as VALIDITY_PERIOD_MNTH,
NULL as WARRANTY_CODE,
NULL as VENDOR_PROD_LINE,
NULL as LOC_MFR,
NULL as LAST_CHANGED_ON_SS,
NULL as CONFORMITY_VALID_FROM,
NULL as CREATION_DATE_SS ,
NULL as DND_EXPIRY_DATE,
NULL as LAST_SO_DATE,
NULL as PL_ACTIVE_VALID_FROM_HRZN,
NULL as DISTR_CHAIN_VALIDITY_DATE,
NULL as AVERAGE_ARTICLE_AGE,
NULL as HRZN_LOC_FIELD_N1_SS,
NULL as HRZN_LOC_FIELD_N2_SS,
NULL as HRZN_LOC_FIELD_N3_SS,
NULL as HRZN_LOC_FIELD_N4_SS,
NULL as HRZN_LOC_FIELD_N5_SS,
NULL as HRZN_LOC_FIELD_N6_SS,
NULL as HRZN_LOC_FIELD_N7_SS,
NULL as HRZN_LOC_FIELD_N8_SS,
NULL as HRZN_LOC_FIELD_N9_SS,
NULL as HRZN_LOC_FIELD_N0_SS,
NULL as AC_ADJ_COST_MASTERDATA,
NULL as DP_DEALER_PRICE_MASTERDATA,
NULL as LP_ADJ_COST_MASTERDATA,
NULL as PC_ADJ_COST_MASTERDATA,
NULL as BASE_UNIT_OF_MEASURE_SS,
NULL as RATE_UNIT_AC,
NULL as RATE_UNIT_DP ,
NULL as RATE_UNIT_LP ,
NULL as RATE_UNIT_PC ,
NULL as GM_MFR_PART_NBR,
NULL as GM_MFR_NAME,
NULL as GM_LONG_PROD_DESCRIPTION,
NULL as GM_PRODTEXT_SAP,
NULL as GM_SHORT_DESCRIPTION,
NULL as GM_TRADE_PRICE,
NULL as GM_ITEM_CTGRY_GRP ,
NULL as GM_RRP,
NULL as GM_NBR_PRODS_IN_STOCK ,
NULL as GM_STOCK_DELIVERY_DATE,
NULL as GM_PROD_WEIGHT,
NULL as GM_PICTURE_URL,
NULL AS GM_F32,                                                                                                        
case 
    when t1."/BIC/TNMATACFL" = 'X' then true 
    else false 
    end as COUNTRY_LVL_ACTIVITY, 

case 
    when t1."/BIC/TNMATACFL" = 'X' then true 
    else false 
    end as MATERIAL_LVL_ACTIVITY

,SYSDATE() as UPDATE_DATE_UTC
,t4."/BIC/TNSALEORG" as  ADVANCED_SOLUTIONS_SALES_ORG,
'6.8' AS ORIGINAL_SOURCE
from  {{ source('us_cdp_bw_68','TNMATERIL') }}  as t1
join  {{ source('us_cdp_bw_68','TNMATSLS') }} t4
  on t1."/BIC/TNMATERIL" = t4."/BIC/TNMATSLS"         
  and t1.soursystem = t4.soursystem 
  and t1.objvers = t4.objvers
  and "/BIC/TNDISTNCH" = '01' 
left join {{source('us_cdp','TNMANUFAC_TO_TUCZZGMNR_MAPPING_VIEW')}} mfg_map
  on t1."/BIC/TNMANUFAC" = mfg_map."/BIC/TNMANUFAC"
left join {{source('us_cdp','GLBL_MFR_TO_VENDOR_CIS_MAPPING_VIEW')}} cis_map
  on mfg_map.glbl_mfr = cis_map.glbl_mfr  
where t1.soursystem = 'A2'

--part 3 cis
UNION ALL 

select
md5(concat('CIS_US', sku_no)) as pkey_material
, 'CIS_US' as SOURSYSTEM
, to_char(SKU_NO) as MATERIAL_ID
, NULL as OBJECT_VERSION
, NULL as SALES_ORG
, NULL as DISTR_CHANNEL
, NULL as MATERIAL_OD_SALES
, NULL as SOURCE_SYSTEM
, case when ACTIVE_STATUS = 'A' then TRUE else FALSE end as ACTIVE_FLAG
, NULL as UN_NBR_NA
, case when ACTIVE_STATUS = 'D' then TRUE else FALSE end as ARCHIVE_FLAG
, case when PROD_TYPE = 'K' then TRUE else FALSE end as MATERIAL_IS_BUNDLE
, FAMILY as CNET_LVL_1
, CATEGORY as CNET_LVL_2
, SUB_CATEGORY as CNET_LVL_3
, NULL as CNET_LVL_4
, NULL as CNET_LVL_5
, NULL as CNET_LVL_6
, NULL as CNET_LVL_7
, NULL as CNET_LVL_8
, NULL as COMPUTER_CHANNEL
, NULL as COMPETITORS
, NULL as DELETION_FLAG
, NULL as DIVISION
, NULL as EUROPEAN_ARTICLE_NBR
, NULL as PURCHASING_VALUE_KEY
, NULL as EXTERNAL_MATERIAL_GRP
, NULL as PROD_FAMILY
, NULL as GOALING_GLBL_MFR
, NULL as HAZARDOUS_MATERIAL
, NULL as HRZN_LOC_FIELD_S0
, NULL as HRZN_LOC_FIELD_S1
, NULL as HRZN_LOC_FIELD_S10
, NULL as HRZN_LOC_FIELD_S11
, NULL as HRZN_LOC_FIELD_S12
, NULL as HRZN_LOC_FIELD_S13
, NULL as HRZN_LOC_FIELD_S14
, NULL as HRZN_LOC_FIELD_S15
, NULL as HRZN_LOC_FIELD_S16
, NULL as HRZN_LOC_FIELD_S17
, NULL as HRZN_LOC_FIELD_S18
, NULL as HRZN_LOC_FIELD_S19
, NULL as HRZN_LOC_FIELD_S2
, NULL as HRZN_LOC_FIELD_S20
, NULL as HRZN_LOC_FIELD_S21
, NULL as HRZN_LOC_FIELD_S22
, NULL as HRZN_LOC_FIELD_S23
, NULL as HRZN_LOC_FIELD_S24
, NULL as TM1_VENDOR
, NULL as HRZN_LOC_FIELD_S26
, NULL as HRZN_LOC_FIELD_S27
, NULL as HRZN_LOC_FIELD_S3
, NULL as HRZN_LOC_FIELD_S4
, NULL as HRZN_LOC_FIELD_S5
, NULL as HRZN_LOC_FIELD_S6
, NULL as HRZN_LOC_FIELD_S7
, NULL as HRZN_LOC_FIELD_S8
, NULL as HRZN_LOC_FIELD_S9
, NULL as INDUSTRY_SECTOR
, NULL as NO_CNET
, NULL as CLOUD_PRODLH
, NULL as TS_TD_COMMON_MATERIAL
, NULL as MFR_DESCRIPTION
, MFG_PARTNO as MFR_PART_NBR
, NULL as MATERIAL_CTGRY
, NULL as MATERIAL_GRP
, NULL as MATERIAL_TYPE
, NULL as MFR_PART_NBR_CLEANED
, NULL as CROSS_PLANT_MATERIAL
, NULL as MULTI_PACK_NBR
, NULL as NEW_STRATEGIC_SOLUTION
, CATEGORY as PROD_CLASS
, NULL as PROD_HRCHY
, NULL as PROD_SERVICE
, NULL as SIZE_DIMENSION
, NULL as SOLUTION_CTGRY
, NULL as SOLUTION_PORTFOLIO
, VPL_CODE as PROD_SUBCLASS
, NULL as TS_MATERIAL
, NULL as VENDOR_PART_NBR_EXTENSION
, NULL as VENDOR_PART_NBR
, NULL as WW_FAMILY_NAME
, NULL as WW_CLASS_NAME
, NULL as HP_PROD_HRCHY_LVL_1
, NULL as HP_PROD_HRCHY_LVL_2
, NULL as HP_PROD_HRCHY_LVL_3
, NULL as HP_PROD_HRCHY_LVL_4
, UNIVERSAL_VEND_NAME as GLBL_MFR
, NULL as LAST_CHANGED_ON
, matl.ENTRY_DATETIME as CREATION_DATE
, NULL as CROSS_PLANT_MAT_VALID
, NULL as DATA_ANALYTICS_LH
, NULL as DATA_CENTER_LH
, NULL as IOT_LH
, NULL as ESTIMATE_GROSS_WEIGT
, NULL as GROSS_WEIGHT
, NULL as HEIGHT
, NULL as HRZN_LOC_FIELD_N1
, NULL as HRZN_LOC_FIELD_N10
, NULL as HRZN_LOC_FIELD_N11
, NULL as HRZN_LOC_FIELD_N12
, NULL as HRZN_LOC_FIELD_N13
, NULL as HRZN_LOC_FIELD_N14
, NULL as HRZN_LOC_FIELD_N15
, NULL as HRZN_LOC_FIELD_N16
, NULL as HRZN_LOC_FIELD_N17
, NULL as HRZN_LOC_FIELD_N18
, NULL as HRZN_LOC_FIELD_N19
, NULL as HRZN_LOC_FIELD_N2
, NULL as HRZN_LOC_FIELD_N20
, NULL as HRZN_LOC_FIELD_N21
, NULL as HRZN_LOC_FIELD_N22
, NULL as HRZN_LOC_FIELD_N23
, NULL as HRZN_LOC_FIELD_N24
, NULL as HRZN_LOC_FIELD_N25
, NULL as HRZN_LOC_FIELD_N26
, NULL as HRZN_LOC_FIELD_N27
, NULL as HRZN_LOC_FIELD_N28
, NULL as HRZN_LOC_FIELD_N29
, NULL as HRZN_LOC_FIELD_N3
, NULL as HRZN_LOC_FIELD_N4
, NULL as HRZN_LOC_FIELD_N5
, NULL as HRZN_LOC_FIELD_N6
, NULL as HRZN_LOC_FIELD_N7
, NULL as HRZN_LOC_FIELD_N8
, NULL as HRZN_LOC_FIELD_N9
, NULL as HRZN_LOC_FIELD_N0
, NULL as LENGTH
, NULL as NET_WEIGHT_OF_ITEM
, NULL as VOLUME
, NULL as WIDTH
, NULL as MOBILITY_LH
, NULL as SECURITY_LH
, NULL as TRAINING_EDUCATION_LH
, NULL as BASE_UNIT_OF_MEASURE
, NULL as CONTENT_UNIT
, NULL as ORDER_UNIT
, NULL as UNIT_LENGTH_WDTH_HEIGHT
, NULL as WEIGHT_UNIT
, NULL as VOLUME_UNIT
, NULL as OLD_ARTICLE_NBR_40
, NULL as ARCHIVE_FLAG_SS
, NULL as CALC_MAT_PRICING_GRP
, NULL as DELETION_FLAG_SS
, NULL as DND_REASON
, NULL as DELIVERING_PLANT
, NULL as ECC_PROD_GRP
, NULL as MRP_FORECASTER
, NULL as NO_FREIGHT_3RD_PARTY
, NULL as EC_DO_NOT_DISPLAY_IR
, NULL as HRZN_REWORK_BUNDLING
, NULL as GLBL_CLOUD_FLAG_108
, NULL as HRZN_CLOUD_62_FLAG
, NULL as HRZN_COPY_SETTING
, NULL as HRZN_MOB_DEVICE_ACTIVATION
, NULL as HRZN_LOC_FIELD_S0_SS
, NULL as HRZN_LOC_FIELD_S1_SS
, NULL as HRZN_LOC_FIELD_S2_SS
, NULL as HRZN_LOC_FIELD_S3_SS
, NULL as HRZN_LOC_FIELD_S4_SS
, NULL as HRZN_LOC_FIELD_S5_SS
, NULL as HRZN_LOC_FIELD_S6_SS
, NULL as HRZN_LOC_FIELD_S7_SS
, NULL as HRZN_LOC_FIELD_S8_SS
, NULL as HRZN_LOC_FIELD_S9_SS
, NULL as AUTOTDESK_RECUR_PROD
, NULL as EC_DO_NOT_DISPLAY
, NULL as EC_NOT_ORDERABLE_IR
, NULL as MAINTENANCE_FY19_REV
, NULL as INTOUCH_104_HP_WARRANTY
, NULL as ENT_LIC_AGRMT_FY19_REV
, NULL as ANTIVIRUS_SECUR_FY19_REV
, NULL as SW_BUNDLES_FY19_REV
, NULL as CONFORMITY_FLAG_HRZN
, NULL as PL_ACTIVE_FLAG_HRZN
, NULL as HP_ECAREPACK
, NULL as EC_DO_NOT_DISPLAY_UK
, NULL as EC_NOT_ORDERABLE_UK
, NULL as HRZN_FLAG_47
, NULL as HOT_SKU
, NULL as EC_ALLOC_FLAG_HRZN
, NULL as EC_NO_TAKING_BACK_HRZN
, NULL as CNET_FLAG_NOT_USED
, NULL as EC_APPLE_CARE_PLAN
, NULL as MS_TOUCHWINS_DEVICE
, NULL as EC_DO_NOT_DISPLAY_INTOUCH
, NULL as EC_GAMING
, NULL as EDI_BLOCK
, NULL as DELL_WARRANTY
, NULL as EC_AUTHORIZED_CUST
, NULL as EC_CUST_SPECIFIC
, NULL as HRZN_FLAG_ANALYTICS
, NULL as HRZN_FLAG_DATA_CENT
, NULL as HRZN_FLAG_EDUCATION
, NULL as IOT_FLAG
, NULL as HRZN_FLAG_MOBILITY
, NULL as HRZN_FLAG_NON_TECHN
, NULL as HRZN_FLAG_SECURITY
, NULL as ACCNT_ASSIGN_GRP
, NULL as BUSINESS_MANAGER
, NULL as DIVISION_MANAGER
, NULL as DIRECTOR
, NULL as REPAIR_TIME_DAYS
, NULL as INVESTIGATION_RESULT
, NULL as ITEM_CTGRY_GRP
, NULL as OLD_ARTICLE_NBR
, NULL as MATERIAL_PRICING_GRP
, NULL as PRICING_FLAG_HRZN
, NULL as PROMO_FLAG
, NULL as RECYCLING_FEE
, NULL as EDI_BLOCK_2
, NULL as SND_CLAIM_SERIAL_NBR
, NULL as SND_FLAG
, NULL as CUST_REBATE_EXCLUSIVE
, NULL as EU_REQUIRED_FLAG
, NULL as LARGE_DIMENSION_PROD
, NULL as AUTODESK_MULTI_SEAT
, NULL as L_PROD_HRCHY_PART_1
, NULL as L_PROD_HRCHY_PART_2
, NULL as L_PROD_HRCHY_PART_3
, NULL as PROD_HRCHY_SS
, NULL as HRZN_VAT_RATE_SALES
, NULL as VOLUME_REBATE_GRP
, NULL as SALES_NOTICE
, NULL as SALES_ORG_ABC
, NULL as SPECIAL_HANDLING_IND
, NULL as TDIT_FREIGHT_POLICY
, NULL as TDIT_FORECASTER
, NULL as VALIDITY_PERIOD_MNTH
, NULL as SALES_BLOCK_DISTR_CHAIN
, NULL as WARRANTY_CODE
, NULL as VENDOR_PROD_LINE
, NULL as LOC_MFR
, NULL as LAST_CHANGED_ON_SS
, NULL as CONFORMITY_VALID_FROM
, matl.ENTRY_DATETIME as CREATION_DATE_SS
, NULL as DND_EXPIRY_DATE
, NULL as LAST_SO_DATE
, NULL as PL_ACTIVE_VALID_FROM_HRZN
, NULL as DISTR_CHAIN_VALIDITY_DATE
, NULL as AVERAGE_ARTICLE_AGE
, NULL as HRZN_LOC_FIELD_N1_SS
, NULL as HRZN_LOC_FIELD_N2_SS
, NULL as HRZN_LOC_FIELD_N3_SS
, NULL as HRZN_LOC_FIELD_N4_SS
, NULL as HRZN_LOC_FIELD_N5_SS
, NULL as HRZN_LOC_FIELD_N6_SS
, NULL as HRZN_LOC_FIELD_N7_SS
, NULL as HRZN_LOC_FIELD_N8_SS
, NULL as HRZN_LOC_FIELD_N9_SS
, NULL as HRZN_LOC_FIELD_N0_SS
, NULL as AC_ADJ_COST_MASTERDATA
, NULL as DP_DEALER_PRICE_MASTERDATA
, NULL as LP_ADJ_COST_MASTERDATA
, NULL as PC_ADJ_COST_MASTERDATA
, NULL as BASE_UNIT_OF_MEASURE_SS
, NULL as RATE_UNIT_AC
, NULL as RATE_UNIT_DP
, NULL as RATE_UNIT_LP
, NULL as RATE_UNIT_PC
, NULL as GM_MFR_PART_NBR
, NULL as GM_MFR_NAME
, LONG_DESC as GM_LONG_PROD_DESCRIPTION
, NULL as GM_PRODTEXT_SAP
, SHORT_DESC as GM_SHORT_DESCRIPTION
, SUG_RETAIL_PRICE as GM_TRADE_PRICE
, NULL as GM_ITEM_CTGRY_GRP
, NULL as GM_RRP
, NULL as GM_NBR_PRODS_IN_STOCK
, NULL as GM_STOCK_DELIVERY_DATE
, NULL as GM_PROD_WEIGHT
, NULL as GM_PICTURE_URL
, NULL as GM_F32
, NULL as COUNTRY_LVL_ACTIVITY
, NULL as MATERIAL_LVL_ACTIVITY
, SYSDATE() as UPDATE_DATE_UTC
, NULL as ADVANCED_SOLUTIONS_SALES_ORG,
'CIS' AS ORIGINAL_SOURCE
from {{source('us_cdp_cis_us','DM_PUB_PART_INFO_VIEW_US') }} matl
left join {{ source('us_cdp_cis_us', 'DM_PUB_VENDOR_INFO_VIEW_US')}} vend
  on matl.vend_no = vend.vend_no

